### ISSUE TITLE
Treat "-" as stdin

### ISSUE THREAD

**Issue by sp1ritCS** [Rafostar/clapper#100]
If Clapper is invoked with "-" as file, it should read from stdin (like other GNU applications), rather than trying to read "$PWD/-".

This allows for more straight forward piping:
```sh
streamlink twitch.tv/pimpcsgo 720p60 --stdout | com.github.rafostar.Clapper -
```
rather than 
```sh
[...] | com.github.rafostar.Clapper /dev/stdin
```

**Comment by Rafostar** [comment]
This is gonna depend on finishing and merging gstplaylist branch, as setting and parsing playlist files will be handled a little differently then.
