### ISSUE TITLE
OSD problem in fullscreen with multiple monitors

### ISSUE THREAD

**Issue by mattblaha** [Rafostar/clapper#102]
This is kind of an odd edge case, but I will try to make it clear.

I have to monitors, one 27 inch 1440p and one 13 inch 720p.

If I start a video in clapper, and it starts on the larger monitor, and I drag it to the smaller one, and hit fullscreen, the fullscreen OSD works as expected. However, if I first fullscreen it on the larger monitor, or even first on the 13, then drag back the 27, full screen it there, and drag it back the 13 and full screen it again, the OSD renders incorrectly.

Screenshots attached. It should be obvious what is incorrect.

**Comment by mattblaha** [comment]
![clapper_bug](https://user-images.githubusercontent.com/2476471/126085858-29c4ef8a-9d36-47d7-b027-3eb02f3badad.png)
![clapper_bug_broken](https://user-images.githubusercontent.com/2476471/126085859-2568fd1d-6060-4521-8cc9-bc6a0a72b5d2.png)

**Comment by Rafostar** [comment]
Does any of the said displays has any scaling applied (in your system settings)?

**Comment by Rafostar** [comment]
Actually never-mind, I found where the problem is. And yes, this bug is only reproduceable when one display is below FHD resolution.

**Comment by Rafostar** [comment]
Should be fixed now in git master. You can find Clapper x86_64 Flatpak git builds in GitHub Actions page [here](https://github.com/Rafostar/clapper/actions/workflows/flatpak.yml) if you want to try it.

**Comment by mattblaha** [comment]
Ah fantastic. Yeah I suppose I should have mentioned -- the display running 720p is actually a 1080p display running at 720p specifically because it's nvidia + x11 -- no display scaling.

Tried the flatpak, is indeed seem fixed on my setup, thanks!

Thanks for Clapper generally too -- I just found it a few days ago when I think omgubuntu did a piece about it -- great app!

**Comment by Rafostar** [comment]
Thanks. You can check out [Hardware Acceleration](https://github.com/Rafostar/clapper/wiki/Hardware-acceleration) on the git wiki for info how to enable NVDEC hardware acceleration if you want. Feel free to ask any questions on #clapper-player matrix channel. Cheers!
