### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by Razer0123** [Rafostar/clapper#104]
Just downloaded on Archlinux using Pipewire

Tested it on a video and audio is not working

Any way i could help fix this?

**Comment by Rafostar** [comment]
Which package you have? `clapper` or `clapper-git` from AUR or maybe flatpak?

**Comment by Razer0123** [comment]
Tried both packages from AUR, same result

**Comment by sp1ritCS** [comment]
try reinstalling either

**Comment by Rafostar** [comment]
@Razer0123 

The Arch packages were now updated. There were few missing dependencies in them, so please try reinstalling. Also make sure you have `gst-plugins-ugly` and `gst-libav` installed which are optional, but include some audio codecs.

**Comment by Razer0123** [comment]
Reinstalled but still not working, those codes worked, thanks

**Comment by sp1ritCS** [comment]
These codecs are marked as optional dependencies in the arch package manifest (PKGBUILD). If you have an AUR helper installed it should poll you about if you want to install them. If you use makepkg directly it should tell you that this package has optional dependencies that you might want to install during the build process.
