### ISSUE TITLE
Move hamburger menu to the right

### ISSUE THREAD

**Issue by RPGHank** [Rafostar/clapper#107]
Most GNOME apps, and applications with hamburger menus in general, have the menus on the top-right of the window

**Comment by Rafostar** [comment]
Yes, but most of these apps also have a separate "open file" menu on the left. It was like that here some time ago (when we still had header bar), but now we have it simplified into a single button. I would rather prefer to have "open file" menu on the left, as I am used to it.

Also what you requests would collide with the request to also show it in fullscreen: #68 where it would not look right next to the current time OSD.

**Comment by RPGHank** [comment]
Separating the open and hamburger menu would solve this, without interfering with #68 and or your muscle memory :D but since you probably had your reasons for combining the menus, and as this really isn't much of an issue in the first place, I'll be closing this
