### ISSUE TITLE
Use Flathub Beta channel

### ISSUE THREAD

**Issue by Eonfge** [Rafostar/clapper#11]
He, cool video player! It reminds me a lot of Celluloid, and it would be cool to see how it developers. 

As for early distribution, you can talk to the maintainers at Flathub about providing a beta  channel. That way, you can distribute it to users without having to rely on your own server.

**Comment by Rafostar** [comment]
According to Flathub Beta description I found [here](https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/):

```
The goal of this is to have a way for developers to get
early releases of new stable versions into the hand of regular users.

This isn’t meant to be used for nightly builds, but for releases that has
some level of testing and are expected to mostly work
and be usable to non-developer end-users.
```

And that is why I am forced to have a github hosted repo for the nightlies. I am not even sure if they would even accept the app that needs to recompile the whole GStreamer 1.18 (flathub has 1.16, I need 1.18) with unmerged patches :disappointed:

**Comment by Rafostar** [comment]
Clapper is now on Flathub: [https://flathub.org/apps/details/com.github.rafostar.Clapper](https://flathub.org/apps/details/com.github.rafostar.Clapper).

**Comment by peteruithoven** [comment]
https://github.com/Rafostar/clapper/discussions/15 is a possibly interesting discussion for people stumbling across this issue.
