### ISSUE TITLE
Playback fails: iHD_drv_video.so init failed

### ISSUE THREAD

**Issue by Sebastian-Hirsch** [Rafostar/clapper#111]
### Description

When I try to open an MP4 Video, I am getting a black clapper window and an error message in the console. The video is playable with the mpv flatpak. I added the video file for testing purposes.

![Bildschirmfoto von 2021-07-21 14-27-15](https://user-images.githubusercontent.com/41188546/126488652-8f7ed334-c66d-4732-bd69-791fa4a312e1.png)

[testfile.zip](https://github.com/Rafostar/clapper/files/6855711/testfile.zip)

### Steps to Reproduce

- Open a MP4 Video File by clicking on it

### Expected Result

Clapper should playback the video file normally.

### Systeminfo

OS: Fedora 34
Package: Flatpak
GPU Driver: Intel Mesa Opensource

**Comment by Rafostar** [comment]
Thanks for the detailed report.

Please run below, reproduce and send over the `~/Videos/gst_debug` file it creates:
```sh
GST_DEBUG_FILE=~/Videos/gst_debug GST_DEBUG_NO_COLOR=1 GST_DEBUG=2 flatpak run com.github.rafostar.Clapper
```

**Comment by Sebastian-Hirsch** [comment]
A reboot of the system seemingly fixed the issue. But here is the log output nonetheless:

[gst_debug.txt](https://github.com/Rafostar/clapper/files/6860465/gst_debug.txt)

**Comment by Rafostar** [comment]
Thanks. Current VAAPI implementation does not seem to "play nice" with Intel iHD driver. We will have newer and faster VAAPI based decoders once gstreamer 1.20 is out. Hopefully problems like this one will be fixed then.

**Comment by Sebastian-Hirsch** [comment]
Okay, thanks for the fast response! Good to know this has a chance of getting fixed. It took a while till firefox fixed is vaapi support for the iHD Driver.

**Comment by Rafostar** [comment]
> OS: Fedora 34
> Package: Flatpak
> GPU Driver: Intel Mesa Opensource

Is this still a problem on recent Clapper 0.4.0 Flathub release?

**Comment by Sebastian-Hirsch** [comment]
The new version of clapper seems to fix this issue. But now I have a different message:

![Bildschirmfoto von 2021-09-14 08-15-14](https://user-images.githubusercontent.com/41188546/133204895-bd6997c4-ae98-42a3-a97d-c0d990622970.png)

Is this related to this issue or should I open up a new one?

**Comment by Rafostar** [comment]
Well that is a different issue, but not a Clapper issue per-se.

Here is the upstream issue (with some links to suggestions what might cause/fix this):
[https://github.com/intel/libva-utils/issues/174](https://github.com/intel/libva-utils/issues/174)

Alternatively you can try installing recent Clapper Nightly flatpak (from GitHub Actions page) temporarily to check if any of the updated libraries in it might have fixed this in your case.

**Comment by Sebastian-Hirsch** [comment]
Okay, as everything works fine now on clappers end, I will close this issue.
