### ISSUE TITLE
Feature Request: Option to disable audio pitch correction for playback speed adjustment

### ISSUE THREAD

**Issue by ghost** [Rafostar/clapper#112]
### Description

Clapper has all the features i know and need of mpv besides two. One of them is to disable the audio pitch correction for the adjusted video playback speed. It would be great to have an option at the playback speed area to disable the pitch correction as some videos can have playback issues that can be solved with this feature. With mpv, the config option audio-pitch-correction=no takes care of that.

### Systeminfo

OS: Fedora 34
Package: Flatpak
GPU Driver: Intel Mesa Opensource, iHD VAAPI Media Driver

**Comment by Rafostar** [comment]
> some videos can have playback issues that can be solved with this feature

I am not against such option, but could you elaborate on what kind of issues "Alvin and the Chipmunks" mode can fix?

**Comment by Sebastian-Hirsch** [comment]
Its quite the niche case I know but there are some digitalized family videos I have are kinda broken and the simplest fix was to change the playback speed without pitch correction in the video player. Some videos are just screwed up and this feature could improve that a bit.
there are no chipmunks involved here ;-).

**Comment by Rafostar** [comment]
In latest git this can be set from command line:
```
clapper --audio-filter=none --speed=1.5
```
This will start Clapper without audio filter set, where default one was doing pitch correction. In video "Info" window user can confirm what/if audio filter is applied.

Now everyone can enjoy running Clapper in "Chipmunks" mode ;-)
