### ISSUE TITLE
Make Floating mode stay above on non-GNOME DE

### ISSUE THREAD

**Issue by gre0j** [Rafostar/clapper#118]
I tried Clapper on Fedora 34 Workstation, and it's great. :)

But in elementaryOS 6 (early build) Clapper still goes behind other windows.
Is there a chance or a workaround to get this working?

**Comment by sp1ritCS** [comment]
AFAIK Clapper calls a GNOME specific dbus method in order to be visible above any other windows. (the same thing happens if you right click the headerbar and select "Show over other Windows" (or similar).

Does Pantheon have something similar?

**Comment by Rafostar** [comment]
To be more precise Clapper calls GNOME Shell via DBus which in turn calls Mutter which handles such option (same goes for show on all workspaces), which makes this impossible on any other DE.

Implementing this per each DE (where it might even not be possible) is pointless for an app that specifically targets GNOME desktop. If and only if Wayland gains a special PiP protocol that will allow this, then we can switch to using it to make this possible. AFAIK, web browsers that run under Wayland natively (e.g. Firefox) also struggle to achieve this.

Until that happens, there is nothing that can be done here, and this isn't a player fault but Wayland limitation. There is little merit in implementing this differently for Xorg, as distros are slowly moving to Wayland one by one.

**Comment by Rafostar** [comment]
I will reopen this and treat it as feature request, but as mentioned earlier, unless Wayland and Mutter can handle this differently in an unified way with other DEs, implementation of this is unlikely to happen.

**Comment by Rafostar** [comment]
There is no more of a dedicated "floating mode". Currently app is always "floating" since its now all OSD. Ability to have it always on top is left to the right click context menu. As long as your DE provides an option there, it will work. All my own hacks targeting GNOME were removed, since they were broken for a long time now. For this reason, closing.
