### ISSUE TITLE
playback speed

### ISSUE THREAD

**Issue by bchachar** [Rafostar/clapper#121]
Can we add an icon to change the playback speed [as here](https://user-images.githubusercontent.com/7236157/75761062-af5ed180-5d38-11ea-996c-2b0cbf66e531.png)

**Comment by sp1ritCS** [comment]
You can change the playback speed by pressing on the elapsed time thingy:
 
![Screenshot from 2021-07-25 14-34-07](https://user-images.githubusercontent.com/31540351/126899135-b79af05d-0c43-4c81-82e3-19c9643044b1.png)

**Comment by bchachar** [comment]
oh i was looking for it but couldn't find. it would be better if these small features are mentioned somewhere on page.

**Comment by Rafostar** [comment]
Duplicate of #33
