### ISSUE TITLE
External ASS subtitles

### ISSUE THREAD

**Issue by ai** [Rafostar/clapper#122]
The popular way to watch anime is to have 2 files like `Anime 1.mkv` and `Anime 1.ass`. But when I tried to play it in Clapper, I do not see subtitles switcher.

**Comment by Rafostar** [comment]
ASS subtitles usually are stored with fonts as attachments inside video container. Those are supported. For external ASS, here is the upstream issue: [https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/36](https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/36)

**Comment by Rafostar** [comment]
Until implemented in GStreamer, you can always merge them into mkv container as a workaround. Once implemented there, they should also work here without any changes to the player itself.
