### ISSUE TITLE
Too many subtitles breaks the subtitle selector

### ISSUE THREAD

**Issue by xscd** [Rafostar/clapper#123]
To reproduce:
1) Use youtube-dl (or [yt-dlp](https://github.com/yt-dlp/yt-dlp)) to download a demo video.
2) Kurzgesagt videos have lots of subtitles like https://www.youtube.com/watch?v=BtN-goy9VOY has 89 subtitles
3) ```yt-dlp --embed-subs --convert-subs srt --sub-langs all --remux-video mkv https://www.youtube.com/watch?v=BtN-goy9VOY```
4) Open the video with Clapper and try to select a subtitle.

**Comment by Rafostar** [comment]
This is now fixed.
