### ISSUE TITLE
Very prominent timestamps

### ISSUE THREAD

**Issue by bertob** [Rafostar/clapper#14]
The timestamps in the bottom bar are very prominent currently, which looks weird and can make the seek bar feel constrained at narrow widths:

![image](https://user-images.githubusercontent.com/1908896/99780919-74473d00-2b17-11eb-8a95-ee241dfe15bb.png)

I'd recommend doing something more similar to Totem, i.e. not showing leading zeros where possible, and maybe having one timestamp on each side rather than both on the left.

![image](https://user-images.githubusercontent.com/1908896/99780591-fc791280-2b16-11eb-8c96-8c2afb543ab2.png)

**Comment by Rafostar** [comment]
> not showing leading zeros where possible

Agreed. But I am not sure if time like `0:01/01:20:00` would be more readable? Maybe show them only (for both times) when duration exceeds 1 hour?

> maybe having one timestamp on each side rather than both on the left.

Well, that is not what I had in mind when I was designing this. Originally I wanted to have easy access to language selection so all needed buttons for that are on the right (already quite a few) and timestamps on the left to have seekbar more in the middle. Also the time is already done inside a button (to conserve space). Ideally I am planning to do a popover from it with playback speed control and DnD video playlist.

**Comment by bertob** [comment]
>  Maybe show them only (for both times) when duration exceeds 1 hour?

Yeah, I think that'd be a good start. Another thing that would help is only showing 1 digit for hours when it's a single digit number of hours (which is probably the majority of cases).

**Comment by Rafostar** [comment]
The biggest problem with timestamps at narrow widths (in every media player I have seen) is that they make the seek bar unusable. Also the track selection buttons are taking quite some space to make it usable on mobile phones.

Having seek bar usable on mobile phone is probably top request of everyone. So I added some mobile/narrow friendly transitions to the app bottom controls panel.

Presentation video:
[https://raw.githubusercontent.com/Rafostar/clapper/master/media/screencast-mobile-ui.webm](https://raw.githubusercontent.com/Rafostar/clapper/master/media/screencast-mobile-ui.webm)

Hopefully this will make user experience more enjoyable on narrow widths :smile:

**Comment by Rafostar** [comment]
@bertob 

In the new UI this is done with a separate time and duration labels on the sides of progress bar, so I am marking this issue to be closed when merged. Sharing a screenshot as a heads-up prior to that.

![Screenshot from 2023-11-03 17-43-59_20231122170009](https://github.com/Rafostar/clapper/assets/40623528/d67b35e3-d2f0-4e4e-bd63-08fe97a30927)

**Comment by Rafostar** [comment]
> > In the new UI
> 
> Wait, there's a new UI?

There is! Simplified, consistent, all OSD, while also actually being more easy to use and giving more features at that, adaptive and mobile friendly. I really did my best here, listening to everyone open issues and trying to make something (that I really, really hope) everyone will like and enjoy to use.

This is done on top of new GStreamer playback libraries implementation I did, to make something that is easier to use and works/plays better with GTK4. So yeah, it took a lot of time and effort, but basically... everything is new :smile: (for the better!). See #374
