### ISSUE TITLE
How can I update daily to see the change? [Question]

### ISSUE THREAD

**Issue by bluebyt65** [Rafostar/clapper#15]
Hi, I have installed clapper with Flatpak, how can I update daily to see the change?
I tried "flatpak update" but that doesn't update to the latest clapper on github.
Command I used to install:
flatpak install https://rafostar.github.io/flatpak/com.github.rafostar.Clapper.flatpakref

**Comment by Rafostar** [comment]
If during install, when you were asked to add "rafostar" repo and selected "yes", than you should receive updates automatically (via `GNOME Software` store - my app should also appear there) or you can force update manually via:
```sh
flatpak update com.github.rafostar.Clapper
```

Saying all that, I do not own a server to do the `nightlies` for each git push for Flatpak version. I will be doing the recompiling and pushing updated version manually once every few new features are added and tested at least a little bit by me.

You can check on which commit latest Flatpak is currently by visiting [my flatpak repo](https://github.com/Rafostar/flatpak) and reading latest `Clapper` commit message (compare with this repo commits for a sort of a changelog).

**Comment by bluebyt65** [comment]
Ok thank you very much to take the time to answer my question!
