### ISSUE TITLE
Feature Request: Playback speed shortcut?

### ISSUE THREAD

**Issue by fancybaby404** [Rafostar/clapper#156]
I don't seem to see a way to change the playback speed of my videos. If it isn't a feature, it would be really nice to see it implemented

**Comment by Rafostar** [comment]
Playback speed can be controlled using slider that comes from elapsed time button when clicked. There is no keyboard shortcut for it yet. This feature requires implementing some "notification" popup that shows what the playback speed has become (and other things) after key-press first.

**Comment by fancybaby404** [comment]
Thanks! I didn't know about that feature.

**Comment by Rafostar** [comment]
> Thanks! I didn't know about that feature.

Buttons highlight on hover should be more noticeable on recent 0.4.0 version. So I hope that this feature will be easier to find. I will keep this open and treat this as a FR for keyboard shortcut which indeed is missing (but needs notifications support first).

**Comment by erazemk** [comment]
Any progress on this? Myself and I think others as well would appreciate just having `[` and `]` keyboard shortcuts available to change video speed, even if there is not yet a notification that displays the new speed.

**Comment by Rafostar** [comment]
@erazemk 
There will be some bigger changes coming first in the coming months. Doing this twice before next release would not be efficient. Once what I am working on gets finished and merged here, I hope multiple feature request like this one will be made easier to tackle. Lets get this done right without half measures.

**Comment by Rafostar** [comment]
There is now `<` and `>` shortcut implemented to decrease/increase speed. The same as people are used to from [YouTube keyboard shortcuts](https://support.google.com/youtube/answer/7631406).
