### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by resynth1943** [Rafostar/clapper#16]
This project looks really promising. It's been in my watch list for a while.

I think we should create a website for Clapper, explaining why and how it exists.
We could just use the README with a custom Jekyll theme.

**Comment by resynth1943** [comment]
Something like [Rain](http://jekyllthemes.org/themes/rain/) would be nice.

All it would take is a PR from me that adds a Jekyll file, then you enabling Pages in Settings :smile:

**Comment by Rafostar** [comment]
@resynth1943 

> We could just use the README with a custom Jekyll theme.

I think I did that some time ago :smiley: 
[https://rafostar.github.io/clapper/](https://rafostar.github.io/clapper/)

The about dialog from app also links to that page.

**Comment by resynth1943** [comment]
> https://rafostar.github.io/clapper/

Damn, that looks awesome!
Thanks for your prompt reply. :smile: 
Still keeping an eye on this project, I can see it's going smoothly.
