### ISSUE TITLE
(Xorg) Not able to interact with GNOME Shell while popover menu is active

### ISSUE THREAD

**Issue by 3ship** [Rafostar/clapper#167]
System info:
EndeavourOS (Arch Linux based)
Clapper version 0.4.0-1 (installed from AUR)
GNOME 40.4 - Xorg Session

Steps to reproduce:
1. In clapper open any popover menu (volume slider, burger menu, etc)
2. Click on any item on the GNOME panel; click on other windows; use the top left hot corner of the GNOME desktop; use Super+Tab to switch to a different window

Result: As long as the popover menu in clapper is open, I cannot interact with any other element of the desktop environment.

This happens under Xorg, but not under Wayland.

**Comment by Rafostar** [comment]
Those are standard GTK4 popover menu buttons. Popovers in GTK4 are made differently then they used to in GTK3.

You should be able to reproduce all your popover issues in other GTK4 applications, including the GTK4 example `gtk4-demo` app. If you have any problems with how they work please report those issues on [GTK4 GitLab](https://gitlab.gnome.org/GNOME/gtk).
