### ISSUE TITLE
Persistent popover menu while switching workspaces

### ISSUE THREAD

**Issue by 3ship** [Rafostar/clapper#168]
System info:
EndeavourOS (Arch Linux based)
Clapper version 0.4.0-1 (installed from AUR)
GNOME 40.4 - Wayland Session

Steps to reproduce:

1. In clapper open any popover menu (volume slider, burger menu, etc)
2. Use Ctrl+Alt+arrow key to switch workspaces; alternatively, use the top left hot corner of the GNOME desktop or the Super key and navigate to a different workspace

Result: The opened popover menu persists across workspaces

As described in #167 I cannot switch workspaces or otherwise interact with the GNOME desktop under Xorg, while a popover menu is opened. Therefore I can't determine, if this is a Wayland-specific issue.

**Comment by Rafostar** [comment]
Please see my explanation in your #167 issue, why this is not app fault.

**Comment by 3ship** [comment]
You're right. I was able to reproduce the #167 issue in other GTK4 applications.

This one's a bit weird though: I now noticed that it only happens when I open clapper through `streamlink-twitch-gui'. No idea how that happens.
