### ISSUE TITLE
Taping the fullscreen on the touchscreen pauses the playback

### ISSUE THREAD

**Issue by Ferenc-** [Rafostar/clapper#170]
So far I have only seen this behaviour on an aarch64 touchscreen device running Manjaro 21.08, with Phosh 0.13.1,
as I only have this device with touchscreen, and the issue correlates with touchscreen.

I am running the latest `0.4.0` flatpak from flathub.

When the playback is going and one taps on the fullscreen icon in the upper left corner, the application changes into fullscreen mode, but the playback also stops. 
When I attach a keyboard and a mouse to this device, and just click on the fullscreen or use the keyboard during playback, this doesn't happen.

**Comment by Rafostar** [comment]
Confirmed. I can reproduce this on a touchscreen monitor. Although, for me playback just pauses (and can be unpaused), not stops completely. I am gonna assume that this is what you meant, if you experience something different, please let me know.

**Comment by Ferenc-** [comment]
Yes, I meant to write pause instead of stop. Sorry for that and thanks for confirming the real problem!

**Comment by Rafostar** [comment]
@Ferenc- 

I hope that this is now fixed. Unfortunately I do not own any aarch64 touchscreen devices running Phosh. If you could try this flatpak build: [https://github.com/Rafostar/clapper/actions/runs/1302732122](https://github.com/Rafostar/clapper/actions/runs/1302732122) once it finishes to confirm, that would be great. Also feel free to reopen if still a problem.

**Comment by Ferenc-** [comment]
I see an improvement with the nightly flatpak. After the first cycle of fullscreen on and off, the inadvertent pause doesn't happen anymore, but the very first tap still pauses the playback as a sideeffect.
I would reopen, but I don't seem to have the privilege to do so.

**Comment by Ferenc-** [comment]
Right. I mixed it up.
With [1302732122](https://github.com/Rafostar/clapper/actions/runs/1302732122) it does work perfectly.
Many thanks for the quick fix!
