### ISSUE TITLE
Crash: `gdk_surface_request_layout: assertion 'frame_clock' failed`

### ISSUE THREAD

**Issue by Ferenc-** [Rafostar/clapper#171]
First reproduction:
````
 flatpak run com.github.rafostar.Clapper

(com.github.rafostar.Clapper:2): Gdk-CRITICAL **: 18:17:10.203: gdk_surface_request_layout: assertion 'frame_clock' failed

(com.github.rafostar.Clapper:2): Gdk-WARNING **: 18:17:10.204: The program 'com.github.rafostar.Clapper' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 11431 error_code 3 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
````
Second reporduction some time later:
````
flatpak run com.github.rafostar.Clapper

(com.github.rafostar.Clapper:2): Gdk-CRITICAL **: 18:33:02.268: gdk_surface_request_layout: assertion 'frame_clock' failed

(com.github.rafostar.Clapper:2): Gdk-WARNING **: 18:33:02.268: The program 'com.github.rafostar.Clapper' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 10349 error_code 3 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)


````
It will probably take more provocative testing to figure out what exactly this issue correlates with.
So far what I know is that both of the times I was playing https://www.youtube.com/watch?v=K7eu5dBgN3g, on Ubuntu 21.04
for testing #169. And the second time I clearly remember clicking on the windowed mode icon next to the volume icon,
and right after that the crash has heppend.
Only this is not enough, there are some further conditions that need to apply, as just clicking on that icon doesn't automatically result in such a crash. 

I could try to do more testing later.

**Comment by Ferenc-** [comment]
Closing it as duplicate of #70

**Comment by Rafostar** [comment]
GTK4 has a lot of problems under Xorg that we are prone to here, unfortunately. Also ATM it runs on GLX instead of EGL (GTK4 4.3.1 worked with EGL, 4.4 again does not work, btw), which prevents us from taking advantage of some features like DMABufs. Those are GTK4 issues and cannot be fixed here. None of those crashes happens on Wayland session. Wayland also due to using EGL provides DMABuf path with VAAPI, so performance is much better (lower CPU and GPU usage). If possible I am gonna recommend using Wayland session.
