### ISSUE TITLE
Empty preferences window

### ISSUE THREAD

**Issue by Tuxino88** [Rafostar/clapper#185]
`(com.github.rafostar.Clapper:11229): Gtk-CRITICAL **: 17:15:55.367: Error building template class 'ClapperPrefsWindow' for an instance of type 'ClapperPrefsWindow': .:0:0 Invalid property: ClapperPrefsWindow.can-swipe-back`

![Schermata da 2021-11-25 17-16-07](https://user-images.githubusercontent.com/75674245/143475575-4b04ed66-d13a-4044-bc87-82f14d4bb1a7.png)

- Gtk4 4.4.1
- Libadwaita 1.0.0 alpha 4
- GStreamer 1.19.3

**Comment by Rafostar** [comment]
You are most likely running on git version of libadwaita. This change is described for alpha5:

https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/doc/migrating-between-development-versions.md#migrating-from-alpha-4-to-alpha-5

Until libadwaita goes into "stable API", things like this (in non-flatpak version) gonna keep happening unfortunately :disappointed:

**Comment by Tuxino88** [comment]
> 

ah ok, I remain tuned to the changes of libadwaita :)
