### ISSUE TITLE
Intermittent loss of audio after seeking

### ISSUE THREAD

**Issue by yasharjit** [Rafostar/clapper#186]
There is often times a loss of audio after seeking either ahead or backwards (can happen using a mouse or the arrow keys for seeking). Sometimes it works but most of the times there is an audio loss. This is on v0.4.0 that is available on flathub.

OS: Fedora 35 Workstation

**Comment by Rafostar** [comment]
Few other people also reported such issue on clapper matrix channel. Seems to happen ONLY on Fedora 35. Every other distro including bleeding edge Arch linux or even older Fedora releases do not seem to have this problem.

For now we were able to determinate that this is not a Clapper bug, as the same happens in other applications (reproduced with Totem).

**Comment by yasharjit** [comment]
Just tested Totem and facing the same problem. Surprisingly, not facing this issue on VLC (from Flathub) as I was thinking that wire plumber may be at fault because that is the only thing that has changed in the audio stack from Fedora 34 to 35.

**Comment by legacychimera247** [comment]
hello, reported it on totem's gitlab and devs says it's a general problem happening in other gnome apps, so i guess it will be fixed at some point...

**Comment by Rafostar** [comment]
Reportedly enabling "Only native audio formats" option in Clapper preferences and restarting player helped workaround the problem to **at least some** users. Not much I can do here if same happens in other applications. Just wait until someone fixes the issue at its source.

**Comment by Rafostar** [comment]
Upstream pipewire issue: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1857
Also similar issue reported at gstreamer: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/909

Nothing more can be done inside Clapper, fixing should be done upstream, so closing.
