### ISSUE TITLE
ASS subtitle fonts messed up

### ISSUE THREAD

**Issue by shakakibara12** [Rafostar/clapper#194]
There's some issue with the font in clapper, playing the same video in mpv have no issues with font.
here is a screenshot :

[Clapper](https://i.imgur.com/TZ3utJX.png)
[MPV](https://i.imgur.com/2GdiOSN.png)

i am using clapper from the latest commit from AUR. I can provide the video file too.
Thanks!

**Comment by Rafostar** [comment]
I think that I have this patched in the Flatpak version of the app. Can you try installing from flathub and check if it also has such issue?

**Comment by shakakibara12** [comment]
Just checked, flatpak version of the app doesn't have that issue. Thanks for replying!

**Comment by shakakibara12** [comment]
Hello, i just tried playing a different video and clapper seems to have font issues in this video ( flatpak version )
Here is a screenshot of this video:

[Clapper](https://i.imgur.com/Q0nMF5s.png)
[Mpv](https://i.imgur.com/BAKKcfj.png)

**Comment by Rafostar** [comment]
The issue from the first video is caused by matroska demuxer block size limit. For fixing this outside of Flatpak, if interested, the open discussion about better handling it in GStreamer can be found here: [gstreamer/-/merge_requests/1186](https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1186)

As for your second video, the cause is different. I will look into it in the coming days.

**Comment by Rafostar** [comment]
> Hello, i just tried playing a different video and clapper seems to have font issues in this video ( flatpak version ) Here is a screenshot of this video:
> 
> [Clapper](https://i.imgur.com/Q0nMF5s.png) [Mpv](https://i.imgur.com/BAKKcfj.png)

@shakakibara12 

Mieru! I mean.. I see whats wrong here. This file was created with some up-to-date software that is already new RFC8081 font mime types. It seems that nobody added them to the list of supported mime types inside "assrender" plugin. This should be a very simple fix and I could send them MR right away, but GStreamer GitLab seems to be down recently (cannot clone their repo). I will take care of this once network is up again.

**Comment by shakakibara12** [comment]
> 

Thanks for the explanation! and good to know that it will be fixed easily!

**Comment by Rafostar** [comment]
Done a fix MR for GStreamer: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1481

**Comment by Rafostar** [comment]
@shakakibara12

Fix from above mentioned MR was added to Flatpak version of the app (from Flathub). Update should roll out within next few hours. Hopefully this will fix all problems with ASS fonts in Flatpak version of the app. If you encounter anything more, feel free to let me know.
