### ISSUE TITLE
Librem 5: Not all icons showing correctly

### ISSUE THREAD

**Issue by carlosgonz0** [Rafostar/clapper#196]
Tested on Librem 5 - libadwaita, SOME icons is bad displayed.
Clapper =< v4.1
Example:
![20211230_170348](https://user-images.githubusercontent.com/45316884/147796457-85be8fc0-aa36-42d2-9a99-dda848633371.jpg)

**Comment by Rafostar** [comment]
Is this Flatpak version? What system icon theme you have set?

**Comment by carlosgonz0** [comment]
Yes it is flatpak i wanted to have Clapper unflakpak but it is not possible at the moment for missing gtk4.

**Comment by Rafostar** [comment]
@carlosgonz0

So what icon theme is this? Try changing system icon theme to "Adwaita".

**Comment by carlosgonz0** [comment]
I think that Phosh still not ship theme option, so there not option to change themes on Librem 5

**Comment by Rafostar** [comment]
Check output of:
```sh
gsettings get org.gnome.desktop.interface icon-theme
```

If its not 'Adwaita', then do:
```sh
gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
```

**Comment by carlosgonz0** [comment]
Thank you i will do just now

**Comment by carlosgonz0** [comment]
purism@pureos:~$ gsettings get org.gnome.desktop.interface icon-theme
'HighContrast'
purism@pureos:~$ gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'
purism@pureos:~$

**Comment by carlosgonz0** [comment]
purism@pureos:~$ gsettings get org.gnome.desktop.interface icon-theme
'Adwaita'

**Comment by carlosgonz0** [comment]
Ok the icons work with theme "adwaita", so how supporting the icons of Clapper on "HighContrast" theme?

**Comment by Rafostar** [comment]
OK. So it seems that you have set in your OS "icon-theme" and maybe even "gtk-theme" to 'HighContrast'. This would also explain why the bottom screen bars were white too.

> so how supporting the icons of Clapper on "HighContrast" theme?

There will not be any special icon support per-theme. If some theme is missing icons that are normally available in `Adwaita` theme (which is default/stock GNOME theme), then this will not be considered a Clapper bug. The best that can be done is open the issue/feature request for the missing icons on THAT theme git repo.
