### ISSUE TITLE
Add Basque (eu.po) on Clapper for translation please!

### ISSUE THREAD

**Issue by IngrownMink4** [Rafostar/clapper#202]
I would like to translate Clapper into Basque. I think I could finish translating it in a short time :')

**Comment by Rafostar** [comment]
> I think I could finish translating it in a short time

Added, but there is no need to rush, as I plan to do some major "behind the scenes" changes in Clapper for next stable release, so it will take some time until then.

**Comment by IngrownMink4** [comment]
> > I think I could finish translating it in a short time
> 
> Added, but there is no need to rush, as I plan to do some major "behind the scenes" changes in Clapper for next stable release, so it will take some time until then.

Okay, all right. Anyway, I will translate it slowly and I will try to have it 100% translated by the time you get to the next stable version.

PS: Thanks for creating Clapper! (actually it's my favorite video player <3)

**Comment by Rafostar** [comment]
> Anyway, I will translate it slowly

Sure. Absolutely no need to rush. Take your time.

> PS: Thanks for creating Clapper! (actually it's my favorite video player <3)

Your git profile says that its MPV through :wink:

**Comment by IngrownMink4** [comment]
> > Anyway, I will translate it slowly
> 
> Sure. Absolutely no need to rush. Take your time.
> 
> > PS: Thanks for creating Clapper! (actually it's my favorite video player <3)
> 
> Your git profile says that its MPV though 😉


Oops, you're right! That's because I haven't updated it in a while. I actually enjoy using Clapper much more than MPV 🤭
