### ISSUE TITLE
Can't unmount external disk after playing video using Clapper

### ISSUE THREAD

**Issue by frnmz** [Rafostar/clapper#205]
As the title says, after playing video with Clapper, unmounting external disk will result to error: `"Volume is busy"`.
Even after the Clapper process is gone from system monitor and from `flatpak ps`.
`lsof | grep` resulting to `xdg-document-portal` is the process that keeping the disk busy by opening file that just opened by Clapper:
```
lsof | grep /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee
xdg-docum 4104                            lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 4105 gmain                 lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 4106 gdbus                 lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 4110 fuse\x20m             lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 4111 fuse\x20m             lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 4112 fuse\x20m             lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 4113 fuse\x20m             lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
xdg-docum 4104 8858 pool-/usr             lam   21u      REG               0,72 2856144411       3578 /run/media/lam/3f285e72-9d65-46a8-a57e-a88530e518ee/Anime HQ/A whisker away/A Whisker Away.mkv
```
Killing `xdg-document-portal` process solves the problem.

**Comment by Rafostar** [comment]
Please check if example player from GTK4 demos also reproduces this issue:
```sh
flatpak run --command=sh com.github.rafostar.Clapper
gtk4-demo --run=video_player
```

**Comment by frnmz** [comment]
> Please check if example player from GTK4 demos also reproduces this issue:

Yup the problem can be reproduced using gtk4-demo.

Also I think it's a flatpak problem, see: https://github.com/flatpak/xdg-desktop-portal/issues/689

**Comment by Rafostar** [comment]
If the problem is reproduce-able with `gtk4-demo`, then its something happening somewhere upstream (not in Clapper). It seems like you have found the real culprit in that flatpak issue you linked above, so this can be closed then.

**Comment by Rafostar** [comment]
@frnmz 

Until solved upstream, this can be used to give flatpak full permission (without using portals) to `/run/media` directory:

```sh
flatpak override com.github.rafostar.Clapper --filesystem=/run/media
```

This also makes D&D work from removable devices without waiting for GTK4 port of Nautilus file manager.

**Comment by frnmz** [comment]
> Until solved upstream, this can be used to give flatpak full permission (without using portals, thus working around that portal bug) to /run/media directory:

It does solves the problem.
If there were a fix on portals, how do I revert the change made by this?

**Comment by Rafostar** [comment]
> If there were a fix on portals, how do I revert the change made by this?

```sh
flatpak override --reset com.github.rafostar.Clapper
```
