### ISSUE TITLE
Clapper is using wrong volume scale or isn't it???

### ISSUE THREAD

**Issue by Rafostar** [Rafostar/clapper#21]
Right now player volume scale is `linear`. From what I understand about human hearing perception, volume sliders should usually use `cubic` volume. Otherwise the player volume slider will not reflect the slider inside `GNOME Settings` app (in Sound tab).

Should I switch to `cubic` scale :thinking:? Feedback is welcome here.

**Comment by sp1ritCS** [comment]
I have no idea how human hearing works - I thought that a linear scale makes sense. But If gnome-settings is using a cubic scale I'm guessing that it is the correct scale. 

If it helps with anyone's decision, I've plotted a linear, quadratic/square (unsure how it is called in English) and a cubic scale.
![grafik](https://user-images.githubusercontent.com/31540351/100363827-2fc71000-2ff5-11eb-9943-9a18d781dfef.png)

**Comment by Rafostar** [comment]
@sp1ritCS 

Thanks. Linear is (hopefully) obvious for everyone, but could you write (just update comment with one line) which color is `cubic`, so if someone else is interested to see how it would work?

**Comment by Rafostar** [comment]
Checked on `GTK4` development issues and surprise, surprise... They run into the same problem :laughing: 
[https://gitlab.gnome.org/GNOME/gtk/-/issues/3295](https://gitlab.gnome.org/GNOME/gtk/-/issues/3295)

Also tried doing just that temporarily and then indeed `GNOME Settings` audio volume and player do match each other. So it seems like right thing to do.

Another thing that will change with this is our amplification, cause as seen on above graphs 100% is the same for all plots (current player volume 100% is correct), but if we go above 100% with cubic scale, then our current 200% will be about 125%. Having 200% with 4 times greater value then now would be an overkill probably. So I am thinking to reduce it to 150% which would still be louder then current 200%.

If nobody complains about it (or proves me wrong) until end of the weekend I will go with the change.

**Comment by sp1ritCS** [comment]
Another possibility would be to add a config option to toggle between cubic and linear.

**Comment by Rafostar** [comment]
> Another possibility would be to add a config option to toggle between cubic and linear.

We don't probably want a toggle between "right" and "wrong" implementation :-) The problem here is which is wrong, but it is  starting to look like current was wrong more and more.
