### ISSUE TITLE
X11: Graphic bug when closing full screen mode

### ISSUE THREAD

**Issue by solsticedhiver** [Rafostar/clapper#212]
I don't know if it has been reported before. I can't find it. May be under a more technical name or descrption ?

When in full screen, you double click on image, the player is resized to normal mode, but theere is kind of 2 windows on top of each over. It's best that I join a screenshot:

![Capture d’écran de 2022-02-05 15-54-33](https://user-images.githubusercontent.com/105990/152647224-9ba7a8fb-1431-4892-bb93-262b50327e0e.png)

May be that's me that take this as a bug where it is not ?

The video continues to play normaly in the small rectangle, but is frozen in hte outer part. With the name of the file above (redacted on screenshot)

On archlinux x86_64 latest, clapper-git r951.b189e24-1 on X11/gnome shell

**Comment by Rafostar** [comment]
That's new. Might be some kind of regression in one of the libs we use. Could check if Flatpak version also has this issue? Also what GPU are you using?

**Comment by solsticedhiver** [comment]
It's a integrated one UHD 630 on Intel i5-8500. I'll look at the flatpak nad report back

**Comment by Rafostar** [comment]
> It's ok with the flatpak

Then this does seem like a problem somewhere else and not my bug. Seems like either GTK4 or Mesa issue. Flatpak uses GTK4 ver 4.4 where you most likely are running 4.6.

**Comment by emansom** [comment]
Celluloid experiences a similar issue, might be related. See https://github.com/celluloid-player/celluloid/issues/746

**Comment by Rafostar** [comment]
> Celluloid experiences a similar issue, might be related. See [celluloid-player/celluloid#746](https://github.com/celluloid-player/celluloid/issues/746)

Might be a GTK4 bug, since it reportedly does not happen with Clapper Flatpak. Someone who experiences this with native build using GTK 4.6 build might want to try to build against GTK 4.4 in order to confirm.

**Comment by Rafostar** [comment]
Latest Clapper git has a newly written from scratch GStreamer video sink that does not seem to be affected by this bug.

I updated GTK to 4.6, switched to X11 and tried on my AMD system with both old and new sink. I cannot reproduce this issue anymore with the new sink, while I can reliably do so with the old, legacy one.

**Comment by solsticedhiver** [comment]
Yes. seems to worknow

**Comment by Rafostar** [comment]
> Yes. seems to worknow

Thanks for confirmation. We indeed can close this here then.

Please note, that this bug is still "somewhere" (likely either GTK or mesa). We just use a different method of displaying video which does not seem to be affected by it. People still affected (e.g. in other apps) should try to debug it and report issue upstream nonetheless.

Also, for this and many other reasons (including performance), I still recommend switching over to Wayland session.
