### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by titi8530** [Rafostar/clapper#22]
Icons on headerbar ( floating mode et fullscreen) and others not here. Nice work :)

**Comment by Rafostar** [comment]
Duplicate of #9 

Try changing icon theme to Adwaita.

**Comment by titi8530** [comment]
It's OK with Adwaita. Thanks. Beautiful player.

**Comment by Rafostar** [comment]
> Edit: no progess bar with webm videos.

Player is a "work in progress". Many features not implemented yet. This is unrelated to icons. If you want me to look into it, open a separate issue and provide an example file that does not work for you.
