### ISSUE TITLE
Failed to upload buffer

### ISSUE THREAD

**Issue by JoshTheBlack** [Rafostar/clapper#220]
POP_OS 21.10 64-bit
GNOME 40.4.0
Latest flatpak install.

When trying to play any video (I haven't found one that plays yet) it just shows blank with a timecode of 00:00/00:00.
When launching from command line, I get:
`(com.github.rafostar.Clapper:2): Clapper-CRITICAL **: 13:22:31.277: Error from element /GstPlayBin3:playbin3/GstPlaySink:playsink/GstBin:vbin/GstGLSinkBin:glsinkbin0/GstGLUploadElement:gluploadelement0: Resource not found.
Failed to upload buffer
../subprojects/gst-plugins-base/ext/gl/gstgluploadelement.c(311): gst_gl_upload_element_prepare_output_buffer (): /GstPlayBin3:playbin3/GstPlaySink:playsink/GstBin:vbin/GstGLSinkBin:glsinkbin0/GstGLUploadElement:gluploadelement0
`
I'm attaching a smallish video file and a debug log.
This video plays in both VLC and the default Videos app included with POP_OS

https://user-images.githubusercontent.com/15058509/155383340-55fd3677-5bce-4ebe-973b-289f27f72002.mp4

[clapper_debug.txt](https://github.com/Rafostar/clapper/files/8126876/clapper_debug.txt)
.

**Comment by Rafostar** [comment]
Remove file at: `~/.var/app/com.github.rafostar.Clapper/cache/gstreamer-1.0/registry.x86_64.bin`. Its gonna be rebuild next time you start Clapper. So lets check the output of that rebuild:
```sh
flatpak run --command=sh com.github.rafostar.Clapper
GST_DEBUG=nv*:7 gst-inspect-1.0 nvcodec
```
This needs to be done rigth after removing said file (while it does not exists yet).

**Comment by JoshTheBlack** [comment]
Attached is the output.  There were some errors, then it gave me an output identical to the picture posted above.
[rebuild_debug.txt](https://github.com/Rafostar/clapper/files/8127799/rebuild_debug.txt)

**Comment by Rafostar** [comment]
The output says your Nvidia GPU does not support any codec for hardware acceleration (NVIDIA GeForce 940MX). I did a little research and it seems that this is indeed the case here:

![Screenshot from 2022-02-24 08-44-11](https://user-images.githubusercontent.com/40623528/155480311-9ff17562-fd2d-4a20-bd7c-6933c211f687.png)

Your Nvidia uses Maxwell GM108, so its an unsupported exception.

Your options are 2 then:
1) Switch to running the app and decoding on your Intel HD graphics which is a better GPU here
2) Turn off (set to zero) all `vaapi` and `va` plugins ranks in the Clapper preferences->plugin ranking to force fallback to software decoding (like default Videos app does).

**Comment by JoshTheBlack** [comment]
Thanks for the info.  How do I direct Clapper to use the Intel HD graphics?

With option 2, All the toggles are off under vaapi and va.  Values aren't editable.  If I turn them on, set them to 0, close preferences, then reopen, they are all still on but back to their default value.  I can't seem to find a way to save the changes.

**Comment by Rafostar** [comment]
@JoshTheBlack 

Its an enable value override toggle. So you turn them on (enable override) and write the new value (in your case 0). So leave them on. If I remember correctly GTK4 requires to hit enter if you write new value using keyboard instead +/- buttons for the value to be remembered.

**Comment by JoshTheBlack** [comment]
I couldn't figure that out to save my life.  I did figure out how to set my intel graphics card though, and at least the first test video played.  

The command I used was `sudo flatpak override --env="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=intel" com.github.rafostar.Clapper`

Thanks for all your help!  I'm going to close this ticket.

**Comment by Rafostar** [comment]
> The command I used was sudo flatpak override --env="__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=intel" com.github.rafostar.Clapper

This is a little incorrect. You cannot set 2 env values with single `--env`. Should be:
```sh
sudo flatpak override --env="__NV_PRIME_RENDER_OFFLOAD=1" com.github.rafostar.Clapper
sudo flatpak override --env="__GLX_VENDOR_LIBRARY_NAME=intel" com.github.rafostar.Clapper
```

I do not have Nvidia GPU, so I may be mistaken here, but I think something like below is actually correct. Might be worth adding to the Clapper wiki page.
```sh
sudo flatpak override --env="__NV_PRIME_RENDER_OFFLOAD=1" com.github.rafostar.Clapper
sudo flatpak override --env="__NV_PRIME_RENDER_OFFLOAD_PROVIDER=Intel" com.github.rafostar.Clapper
sudo flatpak override --env="__GLX_VENDOR_LIBRARY_NAME=mesa" com.github.rafostar.Clapper
```
