### ISSUE TITLE
Feature Request: LUT support

### ISSUE THREAD

**Issue by RobotRoss** [Rafostar/clapper#222]
Could LUT support be added please?

I'm a filmmaker and I'm using Clapper on my laptop as a super-convenient way to quickly preview footage that I've shot, but I record in LOG so I can't judge by eye the colour of my image.

I'd like if possible to be able to apply a LUT (from the .CUBE or .3DL format) to the footage in real-time so I can get a better idea of how my footage is looking.

Many thanks!

**Comment by Rafostar** [comment]
> I'd like if possible to be able to apply a LUT (from the .CUBE or .3DL format) to the footage in real-time so I can get a better idea of how my footage is looking.

First of all you would need a GStreamer plugin that allows to do this. I am not aware of such and even if it existed a video player app such as Clapper does not seem like a good place to use it.

This seems like would either need a dedicated software (GUI designed) for such functionality or if you want something simple, then a manually created gstreamer pipeline that plays video while applying filter from file. Although it would be the possible (and easiest) if such plugin worked with playbin and allowed opening video as "uri" and LUT file as "suburi", mixing both along the way.

But once again, you would need a plugin that can do that first. Unless such plugin exists, nothing that can be done about it here anyway.

**Comment by sp1ritCS** [comment]
> Unless such plugin exists

woudn't GNOME Pitivi have such a plugin? I never used Pitivi, but I imagine if anywhere that will have a GST LUT plugin

**Comment by Rafostar** [comment]
> > Unless such plugin exists
> 
> woudn't GNOME Pitivi have such a plugin? I never used Pitivi, but I imagine if anywhere that will have a GST LUT plugin

Dunno if it uses one (haven't used Pitivi either), but this is a good example of a software for filmmakers that would benefit from having such feature. Seems like definitely a better place to integrate it (if it exists) then a video player is.

**Comment by RobotRoss** [comment]
> > > Unless such plugin exists
> > 
> > 
> > woudn't GNOME Pitivi have such a plugin? I never used Pitivi, but I imagine if anywhere that will have a GST LUT plugin
> 
> Dunno if it uses one (haven't used Pitivi either), but this is a good example of a software for filmmakers that would benefit from having such feature. Seems like definitely a better place to integrate it then video player is.

The problem with Pitivi (and any other NLE, e.g. Davinci Resolve or KdenLive) is that they are flat out bad at previewing raw footage on location - they're aimed at a different use case to the one I'm describing here; which is on-location, quick, colour accurate footage previews (hence why a video player would be a better fit) as NLEs usually work with internal footage 'proxies', and don't allow for fullscreen preview.

**Comment by Rafostar** [comment]
Whenever this is good idea or not does not matter right now as without a plugin that can do that it's impossible to achieve here. This should go as feature request for such plugin in GStreamer, not here. Or maybe someone can do an unofficial 3rd party plugin himself. But until then, this is really not actionable and not something that belongs to Clapper repo, thus closing. Once you find such gstreamer plugin it should be possible to run it within Clapper without any changes to the player itself (like other unofficial plugins) otherwise a new issue can be opened about plugin not working, but not a feature request about making such plugin here.

**Comment by Rafostar** [comment]
Dunno if @RobotRoss managed to influence some people to work on this, but it seems there is an open MR adding support for what you want to do: https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/1792
