### ISSUE TITLE
Librem 5: cannot play AV1 format

### ISSUE THREAD

**Issue by carlosgonz0** [Rafostar/clapper#223]
Clapper failed to play videos on the new AV1 video files and OPUS audio files under MATROSKA,

**Comment by Rafostar** [comment]
Hardware info please. What CPU and GPU?

**Comment by carlosgonz0** [comment]
> Hardware info please. What CPU and GPU?

Librem 5 - Byzantium

**Comment by Rafostar** [comment]
> > Hardware info please. What CPU and GPU?
> 
> Librem 5 - Byzantium. Phosh-3.38-gnome-base.

There is ongoing effort in GStreamer for AV1 support. Using today's gstreamer build from git I can play AV1 fine on my desktop. But with software decoding this is gonna be impossible to play smoothly on Librem 5, I am afraid.

**Comment by Rafostar** [comment]
@carlosgonz0 

You can temporarily replace your Clapper package installation with today (or later) Nightly build. It now includes new `rsdav1ddec` element for AV1 decoding. Link: https://github.com/Rafostar/clapper/actions/workflows/flatpak-nightly.yml

With this I am able to play AV1 videos on desktop without losing any frames. I doubt Librem 5 is good enough to handle software AV1 decoding for smooth playback through, but this is a hardware limitation. Video should play to some extend anyway.

**Comment by carlosgonz0** [comment]
@Rafostar 
Thank you i goint test but i do not know how to get the flatpak-nightly package.
The cpu of L5 it strong so Av1 has to be play like a  butter. But a Lib optimized to decode av1 on arm should be fine by using some simd.

**Comment by Rafostar** [comment]
@carlosgonz0 

> Thank you i goint test but i do not know how to get the flatpak-nightly package.

To install go to: https://github.com/Rafostar/clapper/actions/workflows/flatpak-nightly.yml
Select the newest nightly build from the list, after opening selection scroll to bottom and download `com.github.rafostar.Clapper-aarch64` file you find there (must be `aarch64` for Librem 5). File is zipped, after download unzip it.

Install unzipped file:
```sh
flatpak install --user ./com.github.rafostar.Clapper.flatpak
```

Finally run it with:
```sh
flatpak run --branch=master com.github.rafostar.Clapper
```
Or normally from apps list/drawer if this is your only installation of Clapper flatpak (if you uninstalled Flathub version earlier).

**Comment by carlosgonz0** [comment]
Sorry i can not get to download the package-nightly.flatpak  : ( i hate github.

**Comment by carlosgonz0** [comment]
Well after i tell that i hate github i get to download the package, very strange.

**Comment by carlosgonz0** [comment]
Yes AV1 work now. Thank you very very very much @Rafostar.
The av1 videos work very smooth on Librem 5. Once again thank you @Rafostar. :  )

**Comment by carlosgonz0** [comment]
@Rafostar so now Clapper it using the lib dav1d to plugged to gstreamer?

**Comment by Rafostar** [comment]
@carlosgonz0 

> so now Clapper it using the lib dav1d to plugged to gstreamer?

Check the name of the used decoder in the first popup button to the right of progress slider. Should say `rsdav1ddec` if it is used now. This was added only to nightly for now, I need more feedback from users of different hardware like you, to know if it is used and does any difference to consider if it is worth adding it to stable flatpak eventually.

Nightly package is good for testing only, it lacks some other ARM64 related options and patches from stable one, thus unless you really need that AV1 on daily basis, I recommend going back to stable after you are done testing.

**Comment by carlosgonz0** [comment]
Yes it say that it using "rsdav1ddec" decoding.
I really need AV1 on Clapper, i using AV1 on my daily driver so i stay with nightly packages.
I will happy if Clapper include "rsdav1ddec" to stable, as my case it work very good.

**Comment by carlosgonz0** [comment]
Also i wishing Clapper with GSTREAMER 1.21 to use the VPU of the Librem 5 to decode VP9 and H.265. I tested Clapper nightly to see if i can use the VPU but seems still not work, so i not sure what gstreamer version Clapper it using at the moment.
I want to use like: v4l2hvp9dec and v4l2h265dec so i tested Clapper nightly with a VP9 videos and it using vp9dec instead of v4l2hvp9dec supported on Gstreamer 1.21 and Linux 5.17.

**Comment by carlosgonz0** [comment]
> There is no h265 HW decoder in v4l2 codecs yet. We can try to check why VP9 is not picked, but this requires a different issue ticket. This issue is for AV1 only.

Yes you right that h.265 not ready yet but it on WIP. But VP9 it should ready on gstreamer 1.21. @Rafostar what version of gstreamer Clapper it using now?

**Comment by Rafostar** [comment]
Since AV1 is solved in Nightly and there is different issue for VP9, closing this one.
