### ISSUE TITLE
Dark mode becomes light in dark themes

### ISSUE THREAD

**Issue by titi8530** [Rafostar/clapper#23]
Dark Mode stay/become white when global dark theme mode is enable

**Comment by Rafostar** [comment]
Should be fixed in next update for `Adwaita-dark`. Other themes require `GTK4` support.

**Comment by titi8530** [comment]
Thank you for this amazing player.
    Le lundi 7 décembre 2020 à 15:29:18 UTC+1, Rafostar <notifications@github.com> a écrit :  
 
 


Should be fixed in next update for Adwaita-dark. Other themes require GTK4 support.
