### ISSUE TITLE
Floating mode doesn't stay on top of windows: GNOME

### ISSUE THREAD

**Issue by danastasio** [Rafostar/clapper#235]
Hello,

I am using GNOME 42 on Fedora Silverblue 36 with Wayland (though this happened in Fedora 35 w/ GNOME 40 as well) and Clapper does not stay on top of other windows when floating mode is activated.

I installed Clapper via Flatpak, and did not change any of the default permissions.

If you want any logs or anything, let me know and I am happy to provide them - I just don't know what you want.

**Comment by Rafostar** [comment]
GNOME Shell devs removed functionality we have been taking of to make floating window stay on top in recent GNOME Shell versions. No Wayland protocol to do this automatically exists yet.

We now work around this limitation with a GNOME Shell extension: https://extensions.gnome.org/extension/4691/pip-on-top/

**Comment by Rafostar** [comment]
Another option if you do not want to install any extensions would be to right click Clapper window while holding "Super" key and select "Always on Top" option from context menu. Although GNOME Shell Extension that I linked earlier makes it even easier by "just working" :smile: 

Anyway, this is not a Clapper bug and at current time its impossible to handle this here. Once Wayland protocol for this exists, you can open an issue to implement it. Until then you can work around this with one of the mentioned options.

**Comment by sp1ritCS** [comment]
Alternatively you could also write `global.context.unsafe_mode = true` into the GNOME Looking Glass evaluator (Alt+F2 --> lg), then Clapper can execute the D-Bus method required to set itself as Pip window.

AFAIK the extension doesn't work on GNOME 42, you have to add it to the manifest, because GNOME makes extensions deliberately hard to use.

**Comment by Rafostar** [comment]
> AFAIK the extension doesn't work on GNOME 42, you have to add it to the manifest, because GNOME makes extensions deliberately hard to use.

Guess will have to spin up some 42 live ISO, test and resubmit with updated manifest if nothing else changed API-wise. Still not a Clapper bug a not something possible to address on this git.

**Comment by Rafostar** [comment]
Extension was updated to GNOME 42 and new version is available for download from GNOME extensions website: https://extensions.gnome.org/extension/4691/pip-on-top/
