### ISSUE TITLE
Opening a second HEVC video in Clapper brings down my graphics stack

### ISSUE THREAD

**Issue by kozross** [Rafostar/clapper#236]
Unsure if this is a Clapper bug per se, but I can reliably trigger this issue using Clapper. I'm using the latest Flatpak version of Clapper.

Steps to reproduce:

1. Open a HEVC-encoded video using Clapper using Open Files.
2. Watch for a while - any length of time will do.
3. Try to open another video using Open Files.
4. Observe the audio and video struggle for a few seconds, then both die.

The takedown is total: the entire system becomes unresponsive, the display shows garbage, and the audio continues for a while, then dies too. After a reboot, `journalctl -b-1 -t kernel` ends with the following:

```
Mar 21 15:56:45 Emi kernel: [drm:amdgpu_dm_atomic_commit_tail [amdgpu]] *ERROR* Waiting for fences timed out!
Mar 21 15:56:45 Emi kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=1056224, emitted seq=1056227
Mar 21 15:56:45 Emi kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process com.github.rafo pid 22206 thread gjs:cs0 pid 22227
Mar 21 15:56:45 Emi kernel: amdgpu 0000:03:00.0: amdgpu: GPU reset begin!
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Mar 21 15:56:46 Emi kernel: [drm] free PSP TMR buffer
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: MODE2 reset
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: GPU reset succeeded, trying to resume
Mar 21 15:56:46 Emi kernel: [drm] PCIE GART of 1024M enabled.
Mar 21 15:56:46 Emi kernel: [drm] PTB located at 0x000000F400900000
Mar 21 15:56:46 Emi kernel: [drm] PSP is resuming...
Mar 21 15:56:46 Emi kernel: [drm] reserve 0x400000 from 0xf41f800000 for PSP TMR
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: RAS: optional ras ta ucode is not available
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: RAP: optional rap ta ucode is not available
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: SECUREDISPLAY: securedisplay ta ucode is not available
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: SMU is resuming...
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: SMU is resumed successfully!
Mar 21 15:56:46 Emi kernel: [drm] DMUB hardware initialized: version=0x0101001F
Mar 21 15:56:46 Emi kernel: [drm] kiq ring mec 2 pipe 1 q 0
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring kiq_2.1.0 test failed (-110)
Mar 21 15:56:46 Emi kernel: [drm:amdgpu_gfx_enable_kcq.cold [amdgpu]] *ERROR* KCQ enable failed
Mar 21 15:56:46 Emi kernel: [drm:amdgpu_device_ip_resume_phase2 [amdgpu]] *ERROR* resume of IP block <gfx_v9_0> failed -110
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: GPU reset(2) failed
Mar 21 15:56:46 Emi kernel: amdgpu 0000:03:00.0: amdgpu: GPU reset end with ret = -110
Mar 21 15:56:57 Emi kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring gfx timeout, signaled seq=1056227, emitted seq=1056227
Mar 21 15:56:57 Emi kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process com.github.rafo pid 22206 thread gjs:cs0 pid 22227
Mar 21 15:56:57 Emi kernel: amdgpu 0000:03:00.0: amdgpu: GPU reset begin!
```

This can be reproduced consistently. Note that if I close Clapper, then reopen, before trying to open a new video, this does not occur.

Other details that might be relevant:

**Decoder being used:** ``vaapidecodebin``
**GPU:** AMD Ryzen 7 5800U (it's a laptop, so the graphics are onboard)
**Kernel version:** 5.16.15

``vainfo`` yields this:

```
[koz@Emi ~]$ vainfo
vainfo: VA-API version: 1.13 (libva 2.14.0)
vainfo: Driver version: Mesa Gallium driver 21.3.7 for AMD RENOIR (DRM 3.44.0, 5.16.15-arch1-1, LLVM 13.0.1)
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain10             :	VAEntrypointVLD
      VAProfileHEVCMain10             :	VAEntrypointEncSlice
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileVP9Profile0            :	VAEntrypointVLD
      VAProfileVP9Profile2            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
```

**Comment by Rafostar** [comment]
@kozross 

For reproduction steps you said to open HEVC video. Does that mean you do not have this problem with h264? If you don't, then its most likely the same GStreamer `vaapi` plugin bug that was encountered here some time ago with h264 and `vaapidecodebin`.

Try going to Clapper preferences -> tweaks -> plugin ranking -> va. Enable `vah265dec` rank override and set it to high number like 300. Restart player. If done correctly you should see `vah265dec` instead of `vaapidecodebin` being used when next time you open HEVC video. Check if you still reproduce with it.

**Comment by kozross** [comment]
@Rafostar I tried replicating this issue with H264 videos, and could not do so. Likewise, I set the `vah265dec` override, confirmed that it was used for HEVC, and tried replicating this issue: I also could not do so. Basically, this only seems to happen with HEVC using `vaapidecodebin`.

**Comment by Rafostar** [comment]
Well `va` plugins are better then `vaapi` (especially under Wayland). These are new implementation of `vaapi` under GStreamer (called simply `va` to avoid naming conflicts). They are under active development, so not yet enabled by default. Clapper already enables h264 by default and will most likely enable all the remaining ones for next release.

You can open this as an issue on GStreamer gitlab if you want, but as I said we are going to move to `va` for various reasons anyway. If `va` works for you, that's good. If you also happen to be on Wayland then that's the best combination possible at the moment.

**Comment by kozross** [comment]
Yes, I am on Wayland. What things should I prioritize in the meantime to ensure `va` gets used?
