### ISSUE TITLE
flatpak update issue 

### ISSUE THREAD

**Issue by Adithyan007hack** [Rafostar/clapper#241]
Hello 
this happened to me today when if was updating flatpak apps `flatpak update` :
 Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
Applications using this runtime: 
 com.github.rafostar.Clapper

Are you migrating to gnome upper 4x runtime or gnome 40 runtime is okay?

**Comment by Rafostar** [comment]
Clapper was recently updated to GNOME 42 runtime. Please install the update.

**Comment by Adithyan007hack** [comment]
I installed the update now the update has been completed. How can I check if it is using GNOME 42 runtime?

**Comment by Rafostar** [comment]
@Adithyan007hack 
```sh
flatpak info com.github.rafostar.Clapper
```
Should say: `Runtime: org.gnome.Platform/x86_64/41`

**Comment by Adithyan007hack** [comment]
Yes, it is running GNOME 42 runtime 😄
