### ISSUE TITLE
Feature Request: Make repeat button persistant

### ISSUE THREAD

**Issue by DataStream3** [Rafostar/clapper#248]
Greetings!

Thank you to the devs for this wonderful player! I absolutely love it to death!

However, the one thing it's missing to make it perfect, is the ability to automatically enable the repeat feature instead of manually enabling it every time the program is opened. Thank you for your time and consideration regarding this request.

**Comment by Rafostar** [comment]
I am not sure about this. If we start remembering UI settings like repeat, speed, etc. (for consistency). Then the first user action after opening the player will be making sure that video plays at 1x speed and not e.g: 1.01x speed. This would bring more inconvenience then good probably.

Although player should probably restore speed when resuming last video to what it was before.

**Comment by folknor** [comment]
I'm not saying you should emulate https://github.com/celluloid-player/celluloid/ but I just wanted to note that it remembers the repeat status, volume level, and mute setting when you close it. These things are not remembered per-video, they're global "settings", if that makes sense.

Also celluloids repeat button is much more discoverable.
