### ISSUE TITLE
Flatpak: No decoder available for type 'audio/x-dts'

### ISSUE THREAD

**Issue by Rafostar** [Rafostar/clapper#25]
Flatpak package seems to be missing DTS audio plugin.

```sh
0:00:22.553266395     2 0x7f24c0013060 WARN            uridecodebin gsturidecodebin.c:957:unknown_type_cb:<uridecodebin0> warning: No decoder available for type 'audio/x-dts, framed=(boolean)true, rate=(int)48000, channels=(int)6, endianness=(int)4321, depth=(int)16, block-size=(int)512, frame-size=(int)2012'.
```

**Comment by Rafostar** [comment]
To compile `GStreamer` (and avdec) DTS plugins, [libdca](https://www.videolan.org/developers/libdca.html) is needed.
Not sure if this can be included due to DTS patents...

**Comment by resynth1943** [comment]
Couldn't you use the libraries from the host?
Pretty sure that's how to avoid these invasive patents, but IANAL.
openSUSE requires manual installation of codecs before you can play pretty much anything, so...

**Comment by Rafostar** [comment]
> Couldn't you use the libraries from the host?

That is why this is opened as `Flatpak` issue.

`Flatpaks` were designed to be safe. Normally they DO NOT have any access to files on the host system. Normally the only way to play a video in a `Flatpak` app is to select it manually via file chooser which grants the app a read/write permissions to this single file only. I say normally because unfortunately there are `Flatpak` apps (some of them rather popular) that have enabled complete free access to read/write files on the host without user knowledge. Combine that with free access to Network and you probably get an idea how dangerous this can be...

In our case, inside `Flatpak` distribution everything that is needed (GTK4, all codecs, dependencies etc.) must be included. Otherwise that part will be missing and not work. This is an easy "just install and use" solution.

> openSUSE requires manual installation of codecs before you can play pretty much anything

This is only for an app that is not in `Flatpak` format. Right now Clapper can be installed like that too, but it requires the compiling of some additional plugins with patches until they are merged. In this install method, if user had the lib/codecs installed on their own host system it would work.

**Comment by Rafostar** [comment]
This is now handled by FFmpeg libs.
