### ISSUE TITLE
Floating mode is broken (on GNOME)

### ISSUE THREAD

**Issue by Anomalion** [Rafostar/clapper#250]
When I try to enter Floating mode, it just hides the controls, but neither does it stay above other windows nor does it move to the active workspace.
But both of these things have worked in the past.
Since I don’t watch videos in Floating mode that often, but mostly use Fullscreen mode, I don’t know when it stopped working.

Debian GNU/Linux bookworm/sid
GNOME 42
Wayland

**Comment by Rafostar** [comment]
@Anomalion 

It stopped working when recent GNOME Shell versions removed (disabled by default) functionality we have been using. There is no native Wayland protocol for this yet. You can use this extension I made as a workaround on recent GNOME: https://extensions.gnome.org/extension/4691/pip-on-top/

Also fixes Firefox PiP Wayland behavior as an added bonus :wink:

**Comment by Anomalion** [comment]
Solves the issue of staying on top, but how can I enable it to move automatically to the active workspace?

**Comment by Rafostar** [comment]
> Solves the issue of staying on top, but how can I enable it to move automatically to the active workspace?

Press "Super" key (Windows logo key) + right mouse click on the player. Then select "Always on visible Workspace" option. In the future I plan to move this automatic functionality from Clapper to the said extension too, but right now manual user interaction is needed.
