### ISSUE TITLE
Playing video with a full color range instead of limited brings out inaaccurate colors

### ISSUE THREAD

**Issue by RushingAlien** [Rafostar/clapper#251]
![gambar](https://user-images.githubusercontent.com/80886145/164344997-65e13a7b-5661-4c2c-9b35-da585c62d701.png)
It would seem that clapper has issues when a video has an rgb/yuv color range of 0-255 as it still outputs the color as if its a limited range (16-235) making darks too dark and brights too bright.

**Comment by Rafostar** [comment]
Color conversion (format, colorspace, bit depth etc.) happens in upstream GStreamer pipeline elements like `glcolorconvert`. If your video sample shows incorrect colors, you should be able to reproduce this issue with:

```sh
gst-play-1.0 "video.mp4" --videosink=glimagesink
```
