### ISSUE TITLE
Cant play certain mp4 files - Failed to upload buffer

### ISSUE THREAD

**Issue by Hedronmx** [Rafostar/clapper#259]
This is the error I get

```
Error from element /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:vbin/GstGLSinkBin:glsinkbin0/GstGLUploadElement:gluploadelement0: Resource not found.
Failed to upload buffer
../ext/gl/gstgluploadelement.c(311): gst_gl_upload_element_prepare_output_buffer (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:vbin/GstGLSinkBin:glsinkbin0/GstGLUploadElement:gluploadelement0
```

Running clapper 0.4.1 from flatpak on Fedora 36

GTK version: 4.7.0
Adwaita version: 1.1.1
GStreamer version: 1.20.0
GJS version: 1.72.0

**Comment by Rafostar** [comment]
> Running clapper 0.4.1 from flatpak

First of all, the versions you described do not match what is provided in official Flatpak build (from Flathub). GTK mentioned here is some sort of nightly/unstable version (should be 4.4) and GStreamer ver is actaully older then the one I package (1.20.1). Where does this Flatpak comes from? Consider uninstalling all your Clapper flatpak installations and reinstalling from Flathub.

**Comment by Rafostar** [comment]
Other then mentioned above, if you happen to have an Nvidia GPU, then this might be the same issue as #220

**Comment by Rafostar** [comment]
Ignore this commit. I mistakenly mentioned wrong issue number.

**Comment by Hedronmx** [comment]
I installed it from flathub via gnome software. I just did on my laptop right now. I have attached a screenshot.

![image](https://user-images.githubusercontent.com/26935602/168487079-17160628-3956-47cd-9969-3590bfcdda57.png)

![Screenshot from 2022-05-15 10-58-05](https://user-images.githubusercontent.com/26935602/168487092-bf27bc21-ddf7-45ee-8299-b47a9dcb66c1.png)

**Comment by Rafostar** [comment]
> I uninstalled and installed clapper on my desktop (Where the version mismatch happened) and its working now. Showing the exact versions you mentioned

Thanks for the update :+1:
