### ISSUE TITLE
more discoverable way of selecting subtitles

### ISSUE THREAD

**Issue by legacychimera247** [Rafostar/clapper#263]
hello,

i was trying to watch a video and needed external subtitles (an srt file), after looking almost everywhere came on here and found out subtitles play dizzy with playbin3, ok let's disable that, and they were working then, but still i had first to come on here and look for a way to enable them

wouldn't an icon on the bar be more easily discoverable?like the one you have for internal subtitles

on a sidenote, i had to watch the video with totem cause subtitles where completely un-synchronized (despite timing in the srt being right, in fact totem plays them just fine)

**Comment by Rafostar** [comment]
> subtitles play dizzy with playbin3

Playbin3 is not enabled by default and is clearly marked as an experimental option, which means that there are still problems with it. Enabling experimental option and running into some issues with it should not be surprising.

> wouldn't an icon on the bar be more easily discoverable?like the one you have for internal subtitles

I am not entirely sure for what you are asking about. We try to keep things simple so there is no another "open subtitles file" option menu. Just open file. Either video, subtitles or even both at once. Same should work when selecting both files (video + subs) from file manager. I say "should", cause I am aware that this is racy/buggy on mine side of things right now. I have to rework this whole internal API code to make it work right.

Another easy to use option for adding subtitles is simply dropping them into player window, in case of Flatpak this needs Nautilus (file manager) to be ported into GTK4 to work outside of user Videos directory. Its an ongoing effort: https://gitlab.gnome.org/GNOME/nautilus/-/issues/276

> on a sidenote, i had to watch the video with totem cause subtitles where completely un-synchronized (despite timing in the srt being right, in fact totem plays them just fine)

This is a GStreamer bug: https://gitlab.freedesktop.org/gstreamer/gst-plugins-base/-/issues/891 And for the record Totem which also uses GStreamer has (obviously) the same problem: https://gitlab.gnome.org/GNOME/totem/-/issues/506
What you probably did is that you enabled "fast" seeking option in Clapper preferences which makes this bug more visible (bigger de-synchronization). Totem does not support "fast" seeking thus the offset (de-synchronization) is smaller, but its still there. So "normal" seeking mode in Clapper works like Totem making this bug mostly unnoticeable.

**Comment by legacychimera247** [comment]
not complaining about playbin3, i now it's experimental, but i had to search on there how to enable subtitles, maybe a "open subtitles" option in the drop down upper left menu wouldn't be bad, especially considering i thought about drag'n'dropping subtitles but i had playbin3 enabled and the app was crashing, so thought external subtitles were not supported yet...

**Comment by peteruithoven** [comment]
I also struggled with this for a bit but there are plenty of ways, you just have to know/try: 

> Play video with external subtiles by:
> * selecting and opening both video+subs from file chooser/manager
> * dropping subtitles file on player window
> * opening subtiles from file chooser/manager while video plays
> * send their file path/uri to player via WebSocket message

From: https://github.com/Rafostar/clapper/commit/b15b94fc9079b7e52132e0f81195e97ab3e32689
