### ISSUE TITLE
Controlling playback speed 

### ISSUE THREAD

**Issue by blaze1522** [Rafostar/clapper#271]

**Comment by sp1ritCS** [comment]
you can change the playback speed by clicking on the time indicator. that should open a popup with a slider for it.

**Comment by Rafostar** [comment]
Maybe if I add screenshot of it to readme, it will be easier to find. Anyway as mentioned above, the feature is already available. Just click on the elapsed time to see it.

**Comment by Rafostar** [comment]
Duplicate of #33
