### ISSUE TITLE
GNOME 42: Float on all workspaces does not work

### ISSUE THREAD

**Issue by gargullia** [Rafostar/clapper#280]
In native builds from https://aur.archlinux.org/packages/clapper and https://aur.archlinux.org/packages/gnome-shell-extension-pip-on-top-git on the latest GNOME 42, the mode does not work Floating mode mode. When switching to another desktop, the player remains on the table on which it started

Extension enabled
In the settings, I turned on the switch

The flatpack package also does not work

Last Archlinux last Gnome

**Comment by Rafostar** [comment]
> When switching to another desktop, the player remains on the table on which it started

The setting in Clapper preferences controls the D-BUS method that still works, but only with older shell versions. In the future this option will be removed from Clapper and should be moved into the said extension. There is already a request for that: https://github.com/Rafostar/gnome-shell-extension-pip-on-top/issues/5

If window stays on top in floating mode for you, then it works as expected. The remaining all workspaces functionality needs to be done in extension now. As a temporary workaround you can press Super + mouse right button on Clapper window and select "Always on Visible Workspace" option from the menu.

From your description I understood that only showing on all workspaces is your problem, which I described above. Please let me know if staying on top of other windows works, so we can close this here in favor of that already open issue on extension github.

**Comment by gargullia** [comment]
"Always on Visible Workspace" this solves the problem, but if another application uses this, they conflict. I think that it is possible to close the issues
