### ISSUE TITLE
Feature Request: keyboard shortcut for floating mode

### ISSUE THREAD

**Issue by cassop** [Rafostar/clapper#287]
like me, peoples from [mpv](https://mpv.io/) may appreciate ` [ `and ` ] ` for the speed control

**Comment by Rafostar** [comment]
There is already request for speed control open. See: #156 
I would appreciate if we could avoid duplicated issues, so please continue the eventual discussion for speed in said open issue. We do not seem to have a floating mode shortcut request yet through (that you are also requesting for here).

**Comment by Rafostar** [comment]
Speed control via shortcut was added. Separate "floating" mode was removed completely in latest git in favor of being all OSD (always floating), so closing.
