### ISSUE TITLE
Seek keyboard shortcut should be reversed in RTL

### ISSUE THREAD

**Issue by mskf1383** [Rafostar/clapper#288]
In a desktop with RTL language like persian or arabic, the progress bar is right to left. but clapper shortcut is always right for forward and left for backward. this should become reversed when desktop is RTL.
Thanks!

**Comment by Rafostar** [comment]
Fair point. The keyboard shortcuts window should also have reversed descriptions then.

**Comment by Rafostar** [comment]
I will try to correct this as part of a bigger code rewrite/cleanup I have scheduled for 0.6.0 version.
