### ISSUE TITLE
Tweak mobile mode detection?

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#292]
From #291 I learned that my laptop screen is seen as a mobile screen. 

My laptop: [frame.work](https://frame.work/)
Screen: 2256 x 1504 in 13.5" (3:2)
I'm using scaling factor: 2x
This scaling factor leads to a resolution of: 1128 x 752
It's definitely not an ideal screen size+resolution combo. 
More laptop details: https://frame.work/laptop-12-gen-intel

Can we come up with a way where this isn't seen as a mobile screen? 

It actually seems to work just fine at this size:
![Screenshot build in laptop screen](https://user-images.githubusercontent.com/523210/177970690-a4880781-58b8-4f89-a74b-2cb030fda48e.png)

(The UI isn't in mobile mode because of a bug, see: #291)

How I think this is currently being detected:
https://github.com/Rafostar/clapper/blob/9885a2f424e732c57ea02c8723d197c5ca8a0c16/src/widget.js#L621-L622

An article on how web based projects could handle this: https://medium.com/@rchr/detecting-mobile-browsers-with-one-line-of-javascript-109713d5869c
Funnily enough this would see the frame.work screen as a mobile screen... 

Alternatively I'd love another way to check which file is currently being played. Maybe only show the info when the video is paused? 

I forgot to mention this in the other issue, I'm really loving this player. Great work! It's hard to keep things simple & clean.

**Comment by Rafostar** [comment]
I think that you just go overboard with the scaling on your laptop. Considering its 2256x1504 13.5" display, 200% scaling seems like a bit much. In your current screenshot, the UI is clearly too big and if video had subtitles and hours it would make progress bar even harder to use (much shorter). Ideally you should run 1x (for pixel perfect) ratio, but if things are hard to see/read, consider using frictional scaling with something like 1.5x for example. If you do that you will still have full UI at just the right size on your screen.

If we reduce our default 1280 app-pixels value for mobile any further, then smartphone users will come and open a bug with big UI on small mobile screen instead.

**Comment by peteruithoven** [comment]
Alright fair enough. 

The pixel perfect ratio is indeed my main consideration. And the fact that my external monitor is perfect at 200% and I can't easily have a different scaling factor per screen. 

Not seeing the media / file title is actually my biggest issue, so I'll open a new issue for that.

**Comment by Rafostar** [comment]
> An article on how web based projects could handle this: https://medium.com/@rchr/detecting-mobile-browsers-with-one-line-of-javascript-109713d5869c
Funnily enough this would see the frame.work screen as a mobile screen...

@peteruithoven 

With this you have proven yourself, that your current config will make all kinds of apps think that you use mobile. As I mentioned, go with lower scaling, then you will have correct UI and video title everywhere.

**Comment by Rafostar** [comment]
> Not seeing the media / file title is actually my biggest issue, so I'll open a new issue for that.

You can open this as an issue if you want, but it would need input from mobile (smartphone) users how they see it/fit on their screens. Anyway, my point being here that mobile UI is not really meant or your hardware which should be (deserves to be :smile:) using desktop versions of the apps (both this one) and others that might be using mobile incorrectly.
