### ISSUE TITLE
Add more command line arguments

### ISSUE THREAD

**Issue by psydvl** [Rafostar/clapper#294]
For now, if you launch `clapper --help` you'll see not very informative message:
``` shell
$ clapper --help
Usage:
  com.github.rafostar.Clapper [OPTION…]

Help Options:
  -h, --help                 Show help options
  --help-all                 Show all help options
  --help-gapplication        Show GApplication options

$ clapper --help-all
Usage:
  com.github.rafostar.Clapper [OPTION…]

Help Options:
  -h, --help                 Show help options
  --help-all                 Show all help options
  --help-gapplication        Show GApplication options

GApplication options
  --gapplication-service     Enter GApplication service mode (use from D-Bus service files)

```

At least, I expect that [OPTION...] explain itself as video source or `.claps` file
However, there are a list of options I wouldn't mind seeing:

- height, width, top, left for clapper window after start
- pip enable after start
- always-on-top mode
- always on visible workspace mode
- fullscreen mode
- subtitle source
- etc

**Comment by Rafostar** [comment]
Added more command line options (at least important ones), so closing. For anything that is missing, separate/another issue(s) can be opened.

```
height, width, top, left for clapper window after start
pip enable after start
always-on-top mode
always on visible workspace mode
```
These options are impossible to add through, since they depend on display manager (Wayland does not allow this). And we do not hack that in rewritten Clapper code anyway.
