### ISSUE TITLE
Xorg: playback speed dragging issue

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#297]
The playback speed slider seems to jump to a different position when you move the mouse outside of the popup. 

[Screen record from 2022-07-10 12.35.21@2x.webm](https://user-images.githubusercontent.com/523210/178141320-df8b0afc-5c88-4c3e-b5f5-5581309e0627.webm)

**Comment by Rafostar** [comment]
Most likely not a Clapper bug. We do not do anything special here. This is just standard `GtkPopover` with `GtkScale` placed in it. Also, this does not happen on Wayland session where leaving popover causes drag action to simply stop, but on Xorg only. This should be probably reported upstream to GTK4 if it wasn't already.

**Comment by peteruithoven** [comment]
Clear, I'll close the issue.
