### ISSUE TITLE
clapper doesn't respect exif "rotation" value

### ISSUE THREAD

**Issue by darkblaze69** [Rafostar/clapper#310]
e.g. if video is shot vertically and contains the 90 in exif "rotation" field, clapper doesn't rotate it to play vertically.
Celluloid, mpv, vlc, totem etc respect this field.

**Comment by Rafostar** [comment]
Can you share a video sample file to work with?

**Comment by darkblaze69** [comment]
here it is

https://user-images.githubusercontent.com/6976920/186951408-1a4e1f8d-7c90-4649-b206-36eec90ce72f.mp4


https://user-images.githubusercontent.com/6976920/186951415-785379f8-4fa8-45f6-b418-71b3dff47b05.mp4

**Comment by darkblaze69** [comment]
here it is

https://drive.google.com/file/d/1t7OTikoVO7F_R5a8tFQTkElhN9pCxUUL/view?usp=sharing
https://drive.google.com/file/d/18LHbpgbZAp0i2jvVoV7pfVdYdPMeSi2K/view?usp=sharing
