### ISSUE TITLE
Player uses 12h AM/PM instead of system 24h format

### ISSUE THREAD

**Issue by forteller** [Rafostar/clapper#319]
Hi. Thanks for an awesome product! I love it!

I just noticed the upper right corner popover with the clock and at what time the video will be done. Cool feature! But it uses the 12 hour AM/PM format, while I use the 24h format on my system. I'd love it if Clapper could automatically use the time format of the system/OS it's installed on.

Thanks!

**Comment by Rafostar** [comment]
That would be a bug, cause we are supposed to do this already. How does your time look in output of this command:
```sh
gjs -c 'const { GLib } = imports.gi; log(GLib.DateTime.new_now_local().format("%X"));'
```
If you are using Flatpak version of Clapper then also check the same within container (`flatpak run --command=sh com.github.rafostar.Clapper`) to compare.

**Comment by forteller** [comment]
Thanks! 

I run the Flatpak version, yes. Running this command both without and within container gave me the same output:

kl. 23.53 +0200

**Comment by Rafostar** [comment]
That is an unusual time format, but yes we do not handle that properly, so its our bug.

**Comment by Rafostar** [comment]
Latest UI was simplified and aims at consistency between both windowed and fullscreen window. For this reason clock was removed. Since there is no clock, this issue is closed.
