### ISSUE TITLE
Subtitles files detection?

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#320]
When watching multiple files it's quite a hassle to select the matching subtitle file every time. This while usually there is some consistency to where they can be found. 

For example:
- `./Subs/*.srt`
- `./Subs/Same name/*.srt`

Maybe all these subtitles could automatically be loaded in the subtitle selection menu? 

I realize this depends on: https://github.com/Rafostar/clapper/issues/109

Future upgrade: Since the names of the files is often consistent and indicative of the language, maybe it could then auto select the file with the same name of the subtitle that was selected previously.

**Comment by Rafostar** [comment]
> When watching multiple files it's quite a hassle to select the matching subtitle file every time.

Well, there were plans to have an option to auto select subtitle matching OS language, but that's mostly for embedded subtitles within video container.

> Maybe all these subtitles could automatically be loaded in the subtitle selection menu?

Auto opening of subtitles will be problematic for Flatpak version of the app. We would have to give free access to user filesystem, resulting in apps stores marking this app as very, very dangerous along the way, people being concerned about their private files safety, etc. Not sure if it's right thing to do or if it's gonna be worth it once we get rid of remaining subtitle opening bugs and have D&D from file manager working to add them.

**Comment by peteruithoven** [comment]
> Auto opening of subtitles will be problematic for Flatpak version of the app. We would have to give free access to user filesystem, resulting in apps stores marking this app as very, very dangerous along the way, people being concerned about their private files safety, etc. 

That's a very good point, that I should have considered. That seems unacceptable. 
Alternatively you'd need to select a folder to search subtitles in, which would then increase the hassle of it all again. 
I'll close the issue. 

> D&D from file manager working to add them
What do you mean with D&D?

**Comment by Rafostar** [comment]
> What do you mean with D&D?

Drag and drop.
