### ISSUE TITLE
Include GStreamer dav1ddec in Flatpak

### ISSUE THREAD

**Issue by kdwk** [Rafostar/clapper#326]
# Problem
The default decoder for AV1 videos in Clapper, av1dec, is slow and inefficient, resulting in stuttering when playing back 1080p24 AV1 videos on my Intel  i7-10510U.
# Proposal
Support [dav1ddec](https://gstreamer.freedesktop.org/documentation//dav1d/index.html?gi-language=c) from VideoLAN, a fast and efficient software AV1 decoder, to decode AV1 videos by default.

**Comment by Rafostar** [comment]
There is no support this or that element in this case, if you have it installed it will work.

You did not say what package you are using, but in case of Flatpak container (where everything needs to be included) it is missing because its part of plugins written in Rust that runtime does not include. And compiling them as part of every Flatpak media app you might have does not seem plausible to me (its gonna pull a ton of the same Rust stuff for every package).

**Comment by kdwk** [comment]
Thanks for clearing this up. Is it possible for the org.gnome.Platform runtime to include this instead?

**Comment by Rafostar** [comment]
> Thanks for clearing this up. Is it possible for the org.gnome.Platform runtime to include this instead?

My reasoning here is that it would be best if it was included as part of freedesktop runtime (repo link: [freedesktop-sdk](https://gitlab.com/freedesktop-sdk/freedesktop-sdk)) the same way as all other GStreamer plugins are there. Then all apps would benefit from it. Dunno if this was asked/requested there earlier.

2nd best choice (if they disagree for some reason) would be to have someone make it into a Flatpak extension on Flathub. Then apps that need it could include it in their build manifest.

@kdwk 
If you want to test `dav1ddec` right now, then Flatpak Nightly x86_64 packages build by GitHub Actions [here](https://github.com/Rafostar/clapper/actions/workflows/flatpak-nightly.yml) includes it. Bear in mind that those are highly unstable builds with things possibly broken/not working correctly only meant for testing. They do what I would rather not do for stable release, so pull all Rust deps and build it from scratch, thus doubling build time and tripling package size.

**Comment by kdwk** [comment]
https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1502
Ah, I see there's a plan for that. Thanks for your help.

**Comment by Rafostar** [comment]
> https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1502
> Ah, I see there's a plan for that. Thanks for your help.

Good that GStreamer guys opened themselves an issue there about it. Hopefully it will be moving forward.

**Comment by kdwk** [comment]
![Screenshot from 2023-01-25 14-43-59](https://user-images.githubusercontent.com/39268094/214497896-dbfd02a4-58a4-4737-8b29-89f445e74835.png)
I saw this in the Gstreamer 1.22 release notes. Does that mean dav1d will work out of the box now?

**Comment by Rafostar** [comment]
I already answered your question on Clapper matrix channel, but will leave a comment here too in case someone else will have the same question while browsing issues.

In case of Flatpak as mentioned in freedesktop-sdk issue you linked above, they plan to include it in next runtime release, so 23.08. Clapper flatpak nightlies from GitHub actions (x86_64) includes it, but remember that those are highly unstable.
