### ISSUE TITLE
Streamed YouTube videos oscillate between 1080p and 144p

### ISSUE THREAD

**Issue by kdwk** [Rafostar/clapper#328]
In the latest Flatpak artifact, streamed YouTube videos switch between 1080p and 144p every few seconds. Clapper is maximized on the screen, resolution 1920*1080.

**Comment by Rafostar** [comment]
> latest Flatpak artifact

Not a Clapper bug. The "nightly" artifacts are build from latest GStreamer git and do not include any patches (fixes) applied. Things are patched only in stable Flathub releases or in [non-nightly artifacts](https://github.com/Rafostar/clapper/actions/workflows/flatpak.yml).

When it comes to youtube integration, list of currently known issues with unpatched GStreamer can be found [here](https://github.com/Rafostar/gtuber/issues/36). The problem you are experiencing is listed there in dashdemux issue number 2.

**Comment by Rafostar** [comment]
Closing as not Clapper bug, but feel free to reopen if it also happens to you with patched version of GStreamer.
