### ISSUE TITLE
Option for preferred audio and subtitle language

### ISSUE THREAD

**Issue by whyiseveryfuckingnameisalreadyused** [Rafostar/clapper#329]
Option to set an audio and subtitle language in clapper to auto select the preferred audio track at the start of the video if there are multiple audio or subtitle tracks.

**Comment by Rafostar** [comment]
I updated #308 to also mention audio. Lets use that earlier issue and mark this as duplicate.

**Comment by Rafostar** [comment]
Duplicate of #308
