### ISSUE TITLE
Feature request: Playback Speed

### ISSUE THREAD

**Issue by Shadear** [Rafostar/clapper#33]
Hello and thanks for this awesome project, I am using it since you announce it on r/gnome very nice and much better than celluloid or totem.

One feature that would be nice to have is playback speed, so we can change between 2x, 1.75x, 1.5x, 1.25x, 1x, 0.75x, 0.5x, 0.25x

**Comment by Rafostar** [comment]
> I am using it since you announce it on r/gnome very nice

Thanks for being an early tester.

Playback speed will be definitely added. Playback speed and video playlist are planned to be located in the popover from the elapsed time. That is why it was designed to be a button from the very beginning (I am conserving space for mobile/narrow widths).

**Comment by Shadear** [comment]
Amazing! Looking forward to it.

**Comment by Rafostar** [comment]
I added playback speed in the form of a slider. Allows setting playback speed freely within a range between 0.01x - 2x. As of now looks like this:

![Screenshot from 2021-01-19 16-27-30](https://user-images.githubusercontent.com/40623528/105055451-5f354e80-5a73-11eb-92fe-690a3a9e4c43.png)

**Comment by Mo8it** [comment]
Thanks for the implementation, but this feature can not be found... I came to Github to know from this issue about how to change the speed. It would be nice to mention it somewhere, thanks! :)

**Comment by Rafostar** [comment]
@Mo8it 
Since we should add some sort of initial screen instead of showing black when started without video. I was thinking about making it more useful and having some "tips" shown in it. Hopefully people could learn a trick or two from it.
