### ISSUE TITLE
Asking for a quick status update

### ISSUE THREAD

**Issue by sp1ritCS** [Rafostar/clapper#34]
As gtk4 is now in the official arch extra repo,  how far is the process of getting your gstreamer patches merged into upsteam?

**Comment by Rafostar** [comment]
@sp1ritCS 

I did a pinned post describing all known to me non-Clapper issues and a list of Flatpak version patches. If you (or anyone else) has some questions feel free to ask (preferably using GitHub Discussions feature, so we wont need to open a new issue for each discussion).

**Comment by Rafostar** [comment]
I have additionally set up a Matrix room for Clapper related talks: **#clapper-player:matrix.org**

@sp1ritCS 
I think that this is what you wanted some time ago.
