### ISSUE TITLE
Touchpad gesture to scrub timeline is imprecise

### ISSUE THREAD

**Issue by kdwk** [Rafostar/clapper#340]
# Problem

Currently, users can use two-finger swiping with a touchpad to scrub the timeline. However, since this doesn't utilize 1:1 finger tracking, the scrubbing doesn't stick to the fingers, making the scrubbing too imprecise to be useful.

# Proposal

I propose to either use 1:1 finger tracking for timeline scrubbing or disable this touchpad gesture.

**Comment by Rafostar** [comment]
I think this works nicely now. Although I currently tested only on a single touchpad.

**Comment by kdwk** [comment]
Unfortunately trackpad scrubbing does not seek the timeline anymore. The position marker would move to track my fingers, but when I release it will jump right back to the original position, and not perform the seek.

**Comment by Rafostar** [comment]
Ah, then I misinterpreted this issue. What I meant that was implemented is the more precise seeking by doing two finger horizontal scroll gesture with the touchpad anywhere on the video. The gesture to perform on the progress bar itself is indeed missing.

**Comment by kdwk** [comment]
You didn't misinterpret me, but it's not working ;)

Two finger horizontal scroll anywhere on the video leads to the progress bar marker being moved, but after releasing the two fingers the marker immediately snaps back to the original position without actually performing the seek.

**Comment by Rafostar** [comment]
@kdwk 
Can you check if #404 fixes this issue here (you can build from branch or simply download Flatpak artifact)?

Please note, that what we are doing is fixing "two-finger swiping" on either video or seek/progress bar to seek into more precise position. We are not implementing actual "scrubbing" (seeking while dragging) here yet (a separate issue for that already exists).

**Comment by Rafostar** [comment]
The MR fixed the not working scroll touchpad gesture on slider for me, thus merged. It now works like I explained inmy previous comment here, but if you still experience problems or id doesn't work for you, feel free to reopen.
