### ISSUE TITLE
[Update] Gnome 44 Runtime

### ISSUE THREAD

**Issue by BirdInFire** [Rafostar/clapper#347]
Since all dev have a life i let you know that gnome 44 runtime is out on flathub :+1:

**Comment by DaPigGuy** [comment]
#344

**Comment by julianfairfax** [comment]
It's been half a year, and it would probably be a good idea to update the runtime now, because:

> The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
