### ISSUE TITLE
Video pauses automatically and play/pause button stops to work

### ISSUE THREAD

**Issue by soumyaDghosh** [Rafostar/clapper#350]
Whenever I do some fast forward in a video, it simply stops to play. I need to restart clapper to watch that video again. Using clapper from the Ubuntu repo, v0.5.2

**Comment by Rafostar** [comment]
Wayland or Xorg? Nvidia? Also make sure you did not enable any of the experimental options such as pipewire output.

**Comment by soumyaDghosh** [comment]
Sorry, I was late. I use the app in wayland. I have nvidia card in my lappy, but I don't run the app with my dedicated GPU. Also, I haven't enabled any pipewire or other experimental tweaks.

**Comment by Rafostar** [comment]
I heard that Nvidia HW decoding in GStreamer 1.20 is buggy for some (which is currently used by Clapper over VAAPI when available by default), causing issues like yours (might be fixed in 1.22 already).

If you have an integrated Intel/AMD GPU that can do decoding, then go to Clapper preferences -> plugin ranking, find `VA` on the list and enable manual override for every decoder in it (e.g vah264dec) to value 300. Restart the player and check if problem persists.

**Comment by soumyaDghosh** [comment]
Now it's pausing but the audio can often be heard from a previous part of that video or video is playing of a different part and audio of different. And obviously it pauses after sometime

**Comment by soumyaDghosh** [comment]
I am not able to catch any error in terminal.You can do onething. 
1. In Ubuntu install clapper from the repo
2. Start any video
3. Take the slider and fast forward it randomly, forward and then again backward then again forward. After sometime the video will stop

**Comment by Rafostar** [comment]
Have you tried if stock GNOME Videos app (totem) also has similar problem on your system?

**Comment by soumyaDghosh** [comment]
Clicking the same video shows me this in totem

````
(totem:11788): GStreamer-CRITICAL **: 10:59:21.977: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.007: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.021: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.039: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.056: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.073: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.090: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.110: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.126: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.143: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.161: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.178: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.195: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:22.212: gst_buffer_get_meta: assertion 'buffer != NULL' failed

(totem:11788): GStreamer-CRITICAL **: 10:59:23.723: gst_buffer_get_meta: assertion 'buffer != NULL' failed

`````

It shows that it can't find the video

**Comment by Rafostar** [comment]
> It shows that it can't find the video

If you are installing from package manager (not from Flatpak), please ensure that you also have all other extra codecs installed, mainly:
```sh
sudo apt-get install gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-gl gstreamer1.0-pulseaudio
```
Also make sure that all gstreamer packages are updated to latest version.

After you update, delete temporary "registry" cache file at `~/.cache/gstreamer-1.0`. Check if problem still persists in both Clapper and Totem. Cache will be rebuild next time when you start player.

**Comment by soumyaDghosh** [comment]
All of these codecs are already installed. Cleared the cache also. No help. WIll try with Xorg now.

**Comment by Rafostar** [comment]
What is the GStreamer version on your system? Can you check if Clapper installed from Flathub also has the same issue?

**Comment by soumyaDghosh** [comment]
Yes it's 1.2.0. I think that's why this error. Hope 23.04 will fix this.

**Comment by Rafostar** [comment]
FWIW, the `gst_buffer_get_meta: assertion 'buffer != NULL'` problem you see in Totem is supposed to be fixed since 1.20.3, so you should either update or try Flatpak package which has 1.22 already.

**Comment by soumyaDghosh** [comment]
I just checked Ubuntu 22.10 has the 1.20.3 of gstreamer.

**Comment by soumyaDghosh** [comment]
@Rafostar I have been able to create a snap package, but it's facing 3 major issues

It's giving no audio of the video, I have tried with devmode also
It's unable to fetch the video online, url videos
It's not able find libblas, even after I have added a layout for it.

Can you help me debug it. I'll give you all the necessary details and outputs you need.

**Comment by Rafostar** [comment]
@soumyaDghosh 
Can we move this creating SNAP talk into a separate issue? It's really off-topic from original issue of this thread which was play/pause problem. Once it is separate issue, there is a chance that someone else interested in SNAP might find such issue and help. Right now its impossible to find.

**Comment by soumyaDghosh** [comment]
It's okay, I'm closing this then and creating a separate discussion. But, I guess with your help I can fix it. Please just say me which packages are necessary for the sound to play.
