### ISSUE TITLE
Websocket not available over network?

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#362]
I'm trying to make a very simple remote website using the websocket that I could use from my phone to control Clapper on my laptop. 
Both on the laptop itself using `ws://localhost:6446/websocket` works fine,  but going through the network, using the ip of my laptop (`ws://192.168.178.144:6446/websocket`) doesn't seem to work. Also not on [this public websockets test page](https://livepersoninc.github.io/ws-test-page/). 

Any change the websocket (port) isn't exposed on the network?

I'm running Clapper using Flatpak, could that be the issue? 

Current code: https://stackblitz.com/edit/js-uiw7vp?file=index.js

**Comment by Rafostar** [comment]
Yes, it was by mistake set to not listen on all interfaces. Now fixed.

You can try Flatpak build from [here](https://github.com/Rafostar/clapper/actions/workflows/flatpak.yml) with the merged fix.

One thing to note, web browsers do not allow insecure connections from HTTPS (HTTPS -> WS), so we either need to add an option to Clapper to support setting user certificates to enable WSS (if you wish for such a feat, please open separate feature request), alternatively you could host your web page as plain HTTP, or you can temporarily workaround this in Firefox by enabling `network.websocket.allowInsecureFromHTTPS` in `about:config`.

**Comment by peteruithoven** [comment]
Thanks!
