### ISSUE TITLE
Playback speed is hard to find

### ISSUE THREAD

**Issue by ZeyadAttia5** [Rafostar/clapper#367]
I was coming to submit an issue to add a way to change the playback speed when I found that it was already solved!

It is way too unclear whether this feature exists. it's not in the description, or the features list, and there is no easy way to find it in the GUI. I hope that it will be implemented in a clearer way. 
Adding a screenshot of how to increase the playback speed in the software center would help a lot.

Thank you for maintaining this project 💜

**Comment by Rafostar** [comment]
Agreed. I was personally thinking of moving playlist to be revealed by a side OSD button. Then I could move speed there too. This would remove the click menu on time button which seems too hard to find for users (you are not first person with this question). This would also allow to make time button simply change from current time to show remaining on click (an also requested feature).

**Comment by leonardomlouzas** [comment]
@ZeyadAttia5 Could you tell me how to speed up/down the video?

**Comment by Rafostar** [comment]
> Could you tell me how to speed up/down the video?

You need to click on elapsed time, it opens a popover with speed slider to adjust playback speed.
