### ISSUE TITLE
Cannot play certain videos

### ISSUE THREAD

**Issue by AbrarSL** [Rafostar/clapper#373]
Trying to play certain video files results in the app not doing anything. It seems like the app is not doing anything at all. The app does however remain responsive to user interaction.

[clapper.log](https://github.com/Rafostar/clapper/files/12387359/clapper.log)
This file is the result of running `GST_DEBUG=INFO flatpak run com.github.rafostar.Clapper &> clapper.log`

I can email you the file I'm trying to play. GitHub can't fit it in the issue.

The file works fine with mpv/celluloid. Daikhan manages to play it but the signs/songs subtitles stream doesn't work properly which leads me to believe that this is an issue with how embedded fonts are handled.

**Comment by Rafostar** [comment]
Seems to fail to negotiate colorspace conversion for `P010_10LE` format. This might be either a bug in decoder caps negotition or my bug within sink. Would be great if you could try both combinations with/without newer `vah265dec` element to confirm.

Could you copy your video sample to `Videos` folder within user `Home` directory, open shell within Clapper flatpak (`flatpak run --command=sh com.github.rafostar.Clapper`) and check if any of the below works for you (and if yes, which ones):

```sh
GST_DEBUG=3 GST_PLUGIN_FEATURE_RANK=vah265dec:300 gst-play-1.0 --videosink=clappersink "$HOME/Videos/test_video.mkv"
GST_DEBUG=3 GST_PLUGIN_FEATURE_RANK=vah265dec:0 gst-play-1.0 --videosink=clappersink "$HOME/Videos/test_video.mkv"
GST_DEBUG=3 GST_PLUGIN_FEATURE_RANK=vah265dec:300 gst-play-1.0 --videosink="glsinkbin sink=clappersink" "$HOME/Videos/test_video.mkv"
GST_DEBUG=3 GST_PLUGIN_FEATURE_RANK=vah265dec:0 gst-play-1.0 --videosink="glsinkbin sink=clappersink" "$HOME/Videos/test_video.mkv"
GST_DEBUG=3 GST_PLUGIN_FEATURE_RANK=vah265dec:300 CLAPPER_USE_LEGACY_SINK=1 clapper "$HOME/Videos/test_video.mkv"
GST_DEBUG=3 GST_PLUGIN_FEATURE_RANK=vah265dec:0 CLAPPER_USE_LEGACY_SINK=1 clapper "$HOME/Videos/test_video.mkv"
```

**Comment by AbrarSL** [comment]
The 2nd command worked best. The 4th and 6th worked but the performance was horrible.

Logs taken from all the runs:
[6.log](https://github.com/Rafostar/clapper/files/12388018/6.log)
[5.log](https://github.com/Rafostar/clapper/files/12388019/5.log)
[4.log](https://github.com/Rafostar/clapper/files/12388020/4.log)
[3.log](https://github.com/Rafostar/clapper/files/12388021/3.log)
[2.log](https://github.com/Rafostar/clapper/files/12388023/2.log)
[1.log](https://github.com/Rafostar/clapper/files/12388024/1.log)

**Comment by AbrarSL** [comment]
It plays all the files now! :fire:
