### ISSUE TITLE
Missing bottom controls transition on PinePhone Phoc/Phosh

### ISSUE THREAD

**Issue by uniformbuffer** [Rafostar/clapper#38]
Hi, as seen here (https://raw.githubusercontent.com/Rafostar/clapper/master/media/screencast-mobile-ui.webm), the control buttons at the bottom of the screen should hide, but this is not happening on my Pinephone with Phoc/Phosh:

<p align="center">
  <img src="https://user-images.githubusercontent.com/56791634/107063779-0e478900-67db-11eb-8806-892aa2267870.png" height="800">
</p>

![pinephone-screenshot-landscape](https://user-images.githubusercontent.com/56791634/107063830-1dc6d200-67db-11eb-8ca0-86346d747b07.png)

Thanks for listening, have a good day!

PS: the missing icon is caused by my icon theme and has nothing to do with the app ^^

**Comment by Rafostar** [comment]
Also related to this problem is constant warning this user has been getting logged:
```sh
(com.github.rafostar.Clapper:3436): Gdk-WARNING **: 16:52:50.379: GdkToplevelSize: geometry size (960, 583) exceeds bounds (360, 720)
```

The `960, 583` are default dimensions which should be updated and overwritten with current window size, which leads me to assumption that GTK4 window resize detection might not be working correctly on Phosh.

**Comment by Rafostar** [comment]
@uniformbuffer 

Might be fixed now on git pinephone branch. Can you try recompiling from git pinephone branch?
