### ISSUE TITLE
Runtime Update Needed (Flatpak)

### ISSUE THREAD

**Issue by in4matix** [Rafostar/clapper#381]
`Info: org.gnome.Platform//43 is end-of-life, with reason:
   The GNOME 43 runtime is no longer supported as of September 20, 2023. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   com.github.rafostar.Clapper`

**Comment by Ferenc-** [comment]
Duplicate of https://github.com/flathub/com.github.rafostar.Clapper/issues/21, see https://github.com/Rafostar/clapper/pull/344

**Comment by in4matix** [comment]
> Duplicate of [flathub/com.github.rafostar.Clapper#21](https://github.com/flathub/com.github.rafostar.Clapper/issues/21), see #344

Oh okay, sorry my bad

**Comment by in4matix** [comment]
I have found that completely removing Clapper and then reinstalling it again resolves the runtime issue.
