### ISSUE TITLE
[Feature Request] Pasting a link into the window

### ISSUE THREAD

**Issue by RedAuburn** [Rafostar/clapper#384]
it'd be cool if pasting a link to a video (on youtube etc) while clapper is in focus would automatically check and if possible load the video.

**Comment by Rafostar** [comment]
FYI, one thing clapper already supports is drag and drop video image from browser into player. This way video link is send too. Can probably also add a copy-paste you describe, as an alternative.

**Comment by RedAuburn** [comment]
`ctrl+U` works well enough for this imo
