### ISSUE TITLE
Clapper flatpak won't launch on NixOS

### ISSUE THREAD

**Issue by ahydronous** [Rafostar/clapper#389]
The Clapper flatpak currently won't launch unless launched from the Software center or manually via the CLI.

I suspect it is the same problem the Telegram flatpak has, as it exhibits the same issues and is worked around via the same tricks.

Here is the relevant Github issue: https://github.com/telegramdesktop/tdesktop/issues/27134#issuecomment-1830632515 and they have already fixed it

**Comment by Rafostar** [comment]
I do not think this is the same issue here. We do not use Qt but GTK instead.

If this was a fresh install from store, a reboot might fix this. I have actually seen issues where newly installed apps that launch with D-Bus need to restart D-Bus service for it to work with them some reason.

**Comment by ahydronous** [comment]
A reboot did not help, nor did an uninstall + reboot + reinstall + reboot. 

If I click the icon to launch Clapper, it immediately, silently fails to launch. If I try to open an associated media file, it shows a spinner if I hover over my panel, but silently fails after trying for ~15s.

Is there anything I can do to diagnose the issue further?

**Comment by Rafostar** [comment]
In this case, the best place to look at what is going on on your system is probably `journalctl`

**Comment by Rafostar** [comment]
Here is your issue: https://discourse.nixos.org/t/some-flatpaks-fail-to-launch-from-launcher-icon/20818

**Comment by Rafostar** [comment]
Clapper also uses `DBusActivatable=true` to launch via DBus like mentioned there. As far as i see, fix was merged to NixOS not long ago (on October 3): https://github.com/NixOS/nixpkgs/pull/222678

Dunno when these fixes reach end users, not really familiar with NixOS.

**Comment by ahydronous** [comment]
I'll try a nixos-update later tonight. If that doesn't fix it, It'll probably be fixed with 23.11 (current is 23.05 but 23.11 will launch very soon).

Thanks for bearing with me and finding the relevant NixOS problem!

I'll link the relevant issue just for posterity: https://github.com/NixOS/nixpkgs/issues/138956
