### ISSUE TITLE
Warn the user on missing file/folder Flatpak permissions

### ISSUE THREAD

**Issue by nekohayo** [Rafostar/clapper#391]
If I navigate with Nautilus to my `~/some_project/foo` folder, in which I have some video file symlinked to another place in my XDG Videos folder, i.e. something like this: `baz.webm -> /home/my_user/Vidéos/demos/baz.webm`

...trying to play the baz.webm symlink from this folder, Clapper silently fails, it just shows the Clapper window with a black screen and no playback happening.

However, it turns out that it _would_ be able to play that file, just that it didn't have the permissions to do so.   
I had to go into flatseal and add additional filesystem permissions for `~/some_project:ro`

This is not obvious except to the geekiest flatpak users.  
Clapper should show an error dialog with a hint for the solution when this happens / when it is unable to open a file or folder.

**Comment by Rafostar** [comment]
With the ongoing code rework, currently this case would show:

![Screenshot from 2023-12-07 20-32-16](https://github.com/Rafostar/clapper/assets/40623528/62e864df-ad45-48e7-8c12-ae4d5f2620e7)

We cannot really tell apart non-existing file from file we do not have read permissions for.
