### ISSUE TITLE
Flathub warning "Uses an end-of-life runtime" / Stopped receiving updates

### ISSUE THREAD

**Issue by woodsb02** [Rafostar/clapper#393]
The Clapper app [on Flathub](https://flathub.org/apps/com.github.rafostar.Clapper) warns:

![image](https://github.com/Rafostar/clapper/assets/7113557/ed09c8eb-8a4d-4066-8be8-2d870394d263)

In GNOME software, this results in these warnings:

![image](https://github.com/Rafostar/clapper/assets/7113557/e9979bd8-966f-4cc4-925d-4472d814e2c8)

![image](https://github.com/Rafostar/clapper/assets/7113557/a6162d47-5917-450a-8177-e1c736bafa43)

**Comment by woodsb02** [comment]
I believe this is related to this issue: https://github.com/flathub/com.github.rafostar.Clapper/issues/21

And would be fixed by https://github.com/flathub/com.github.rafostar.Clapper/pull/24, once this blocking issue is resolved: https://github.com/Rafostar/clapper/issues/382

**Comment by Rafostar** [comment]
Yes, ideally update to latest but broken/blurry subtitles are a no go. I will check if 44 also has this issue, maybe then we can temporarily move to 44 at least since app rewrite is taking sightly longer then expected...

**Comment by CaptechOmar** [comment]
This warning is present again at the moment
