### ISSUE TITLE
No video , audio only in arch 

### ISSUE THREAD

**Issue by mohammedbilalns** [Rafostar/clapper#400]
I installed Clapper from the AUR. It only plays audio without displaying any video. I've tried both the git version and the stable release.

**Comment by Rafostar** [comment]
You are probably missing one of optional dependences defined in AUR PKG script. Please check you have them installed. That being said, recently released GStreamer 1.24 which already hit Arch linux is not yet well supported. Consider trying Flatpak package of Clapper.

**Comment by Rafostar** [comment]
Recent git now works better with GStreamer 1.24. As long as you have installed all extra packages with codecs and HW decoders, videos should play now.

**Comment by mohammedbilalns** [comment]
Works now. However, there are two weird horizontal lines through the bottom bar (they only appear when the bottom bar is active).

**Comment by Rafostar** [comment]
Might be caused by your theme perhaps? I only target and test stuff with Adwaita.
