### ISSUE TITLE
Provide Rust bindings

### ISSUE THREAD

**Issue by Rafostar** [Rafostar/clapper#411]
Since both Clapper APIs already support GObject introspection with addition of Vala VAPI file generated, it would be awesome if we could also have Rust support generated similarly.

**Comment by jangernert** [comment]
I spent a bit of time this weekend to generate bindings for both clapper and clapper-gtk to use it as part of Newsflash.
I haven't commited the code yet. But I have a working sample already that plays a vp8 file (a bit of trouble with gstreamer-plugins not being detected).

I'm not sure about doing a release on `crates.io` since you mentioned the API is still unstable. For now my plan was to create a repository and use the bindings directly via git.

```
use gtk4::{glib, prelude::*};
use clapper_gtk::{Video, TitleHeader, SimpleControls};
use clapper::MediaItem;

fn main() -> glib::ExitCode {
    glib::setenv("CLAPPER_USE_PLAYBIN3", "1", false).unwrap();
    clapper::init().unwrap();

    let app = libadwaita::Application::new(Some("org.gnome.clapper-rs.example"), Default::default());
    app.connect_startup(|_app| {
        let style_manager = libadwaita::StyleManager::default();
        style_manager.set_color_scheme(libadwaita::ColorScheme::ForceDark);
    });
    app.connect_activate(move |app| {
        let video = Video::new();
        video.set_vexpand(true);
        
        let header = TitleHeader::new();
        header.set_valign(gtk4::Align::Start);
        video.add_fading_overlay(&header);

        let controls = SimpleControls::new();
        controls.set_valign(gtk4::Align::End);
        video.add_fading_overlay(&controls);

        let item = MediaItem::new("file://var/home/jangernert/big-buck-bunny_trailer.webm");
        video.player().unwrap().queue().unwrap().add_item(&item);
        video.player().unwrap().queue().unwrap().select_item(Some(&item));

        let content = gtk4::Box::new(gtk4::Orientation::Vertical, 0);
        content.append(&libadwaita::HeaderBar::new());
        content.append(&video);

        let window = libadwaita::ApplicationWindow::builder()
            .application(app)
            .default_width(600)
            .default_height(400)
            .content(&content)
            .build();

        let window_clone = window.clone();
        video.connect_toggle_fullscreen(move |_video| {
            window_clone.set_fullscreened(!window_clone.is_fullscreened());
        });
        window.present();
    });
    app.run()
}
```

btw: for some reason `CLAPPER_MARKER_NO_END` was `1` instead of `-1` in the gir file for me. That lead to a failing test comparing values with the original. I just patched my gir-file locally.

@Rafostar  What were your intentions here? Have the bindings as part of the clapper repository and maintained by you? Or for something done by a 3rd party like most gnome related bindings?

**Comment by Rafostar** [comment]
> I spent a bit of time this weekend to generate bindings for both clapper and clapper-gtk to use it as part of Newsflash.

That's awesome and a nice surprise :smile: . Thanks for working on this :+1: 

> btw: for some reason CLAPPER_MARKER_NO_END was 1 instead of -1 in the gir file for me.

Thanks for noticing and letting me know, I have now fixed it in git master (https://github.com/Rafostar/clapper/commit/23c5e7ca6510e62b488b3a6af846c1aafd0f8c5d). I plan to do a patch version 0.6.1 release, so I will include it there. But I am still waiting for some more people finding any issues.

> I'm not sure about doing a release on crates.io since you mentioned the API is still unstable. For now my plan was to create a repository and use the bindings directly via git.
> What were your intentions here? Have the bindings as part of the clapper repository and maintained by you? Or for something done by a 3rd party like most gnome related bindings?

To be honest... I dunno! Depends? From one side, it would be easier to have them in monorepo with libraries, app and vala bindings, but only if they can be mostly auto-generated and maintained easily. On the other hand, I feel like I would fail to properly maintain them myself here. Especially considering its a programing language I do not normally work with and there is already a lot of other stuff to do here for me.

Currently I opened this issue as a thing that we "can have" since we already do GIR. But there is no point in having them if there is no application that actually wants/plans to use them. Its also true that current APIs should be treated as unstable, but I will try my best to not break them as much as possible.

So, what I think would be best for the time being is, if you are interested/willing to create a repo to place them, please do so. If that's OK with you, I would simply put a link in the git Readme to them. Then anyone can check them if interested. In future they can always be changed/moved if necessary.

One small correction to the example if I may:
```
let item = MediaItem::new("file://var/home/jangernert/big-buck-bunny_trailer.webm");
```
The URI protocol is `file://` followed by a full path to the media (starting from "/"), so there should be 3 slashes. Other then this nitpick, you did a great job at porting the usage example to Rust language. Thanks!

**Comment by jangernert** [comment]
> To be honest... I dunno! Depends? From one side, it would be easier to have them in monorepo with libraries, app and vala bindings, but only if they can be mostly auto-generated and maintained easily. On the other hand, I feel like I would fail to properly maintain them myself here. Especially considering its a programing language I do not normally work with and there is already a lot of other stuff to do here for me.

Setting them up for the first time is a bit of a hassle. But updating should be considerably more easy.

> Currently I opened this issue as a thing that we "can have" since we already do GIR. But there is no point in having them if there is no application that actually wants/plans to use them. Its also true that current APIs should be treated as unstable, but I will try my best to not break them as much as possible.

Well, I wouldn't worry about that. I generated the bindings because I plan to make use of them. And I foresee a not too distant future where libclapper will become the de facto standard for gnome apps that need video playback.

Here you can read on my experience of implementing a video player in Newsflash (last section): https://blogs.gnome.org/jangernert/2023/09/22/newsflash-3-0/

Its just too much work when video is only one of many things your app does. One of the comments made me aware of your efforts to build something nice that can be shared across apps.


> So, what I think would be best for the time being is, if you are interested/willing to create a repo to place them, please do so. If that's OK with you, I would simply put a link in the git Readme to them. Then anyone can check them if interested. In future they can always be changed/moved if necessary.

Okay, I'll upload what I've got tonight and post the link here.

> One small correction to the example if I may:
> 
> ```
> let item = MediaItem::new("file://var/home/jangernert/big-buck-bunny_trailer.webm");
> ```
> 
> The URI protocol is `file://` followed by a full path to the media (starting from "/"), so there should be 3 slashes. Other then this nitpick, you did a great job at porting the usage example to Rust language. Thanks!

Hm, it works regardless. Thanks though.

**Comment by Rafostar** [comment]
> Here you can read on my experience of implementing a video player in Newsflash (last section): https://blogs.gnome.org/jangernert/2023/09/22/newsflash-3-0/

"Video streaming is hard."

I agree :smile: 

> Okay, I'll upload what I've got tonight and post the link here.

Thanks again.

**Comment by jangernert** [comment]
https://gitlab.gnome.org/JanGernert/clapper-rs

I maybe it can move to https://gitlab.gnome.org/World/Rust at some point. That's where a lot of other rust bindings already are.

Next on my list is to actually make use of it in Newsflash. Hopefully this will unveil any showstopper issues with the bindings.

**Comment by Rafostar** [comment]
@jangernert 

OK. Updated Readme, so this case is closed. Thanks.

> Next on my list is to actually make use of it in Newsflash.

If you have any problems, want to ask anything, something I did/why is unclear (I probably did not do a very good job at initial API/widgets documentation :sweat:) feel free to drop by and ask on Clapper matrix channel anytime. Cheers!
