### ISSUE TITLE
libclapper-0.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by bluebyt** [Rafostar/clapper#412]
I want to install clapper from source since I want this feature "repeat button persistant"
https://github.com/Rafostar/clapper/issues/248

but I get this error when I try to open clapper: As you can see the lib is there?
clapper: error while loading shared libraries: libclapper-0.0.so.0: cannot open shared object file: No such file or directory

![slurped](https://github.com/Rafostar/clapper/assets/18442224/7c8ff64a-6259-4716-a0a9-d0676576443c)

System: Archlinux

**Comment by Rafostar** [comment]
@bluebyt 
Not sure if Archlinux has `/usr/local/lib` in LD config by default. If you want to be running latest git and check out latest features of Clapper, probably best way anyway to do so in Arch linux is to simply install `clapper-git` from AUR. This way you will also get updates.

**Comment by bluebyt** [comment]
I will try clapper-git, but is there a way to uninstall clapper?, since I already installed it with this command. 
meson builddir --prefix=/usr/local
sudo meson install -C builddir

**Comment by Rafostar** [comment]
Open terminal (or navigate to) `builddir` in your Clapper cloned repo. Inside it run: `sudo ninja uninstall`.

**Comment by bluebyt** [comment]
Ok  I installed it from git that work!
I read the Archlinux wiki and I should have installed clapper in the usr folder.
meson builddir --prefix=/usr/
Thanks for you help!

**Comment by gasandjalilov** [comment]
@bluebyt could you share the instruction? meson builddir --prefix=/usr/
doesn't work on pine phone pro with arch linux

**Comment by bluebyt** [comment]
@gasandjalilov I just use clapper-git from aur.
