### ISSUE TITLE
Some keyboard shortcuts do not work on Xorg

### ISSUE THREAD

**Issue by peteruithoven** [Rafostar/clapper#416]
I was trying the [git action builds](https://github.com/Rafostar/clapper/actions/workflows/flatpak.yml) and seeking by pressing the <kbd>←</kbd>/<kbd>→</kbd>/<kbd>L</kbd>/<kbd>J</kbd> keys doesn't seem to work. 
Same for the nightly version. 
Other keys like <kbd>K</kbd> work fine. 
As far as I know there are no other ways to seek? 
I installed [this version](https://github.com/Rafostar/clapper/actions/runs/8711158802)
I'm running on elementary OS 7.1 Horus Built on Ubuntu 22.04.3 LTS.
CPU: Quad-Core 11th Gen Intel® Core(TM) i7-1185G7 @ 3.00GHz
Build in GPU: Intel® TigerLake-LP GT2 [Iris Xe Graphics]
This also means I'm using X11 and not Wayland yet.
I didn't find any seek related issues.

**Comment by Rafostar** [comment]
Oh, great find. Indeed some keybindings do not seem work on Xorg for some reason (volume up/down also doesn't work). All works find on Wayland session, which is very surprising.
