### ISSUE TITLE
Clapper doesn't respect default app for open MP3 files

### ISSUE THREAD

**Issue by Gabryoo3** [Rafostar/clapper#419]
I want to open MP3 files with another app (Decibels), but Clapper forces itself to open mp3 files, and you can't change this behavior even when you set the other app (Decibels) as default. Video for demonstration
[Video del 2024-04-19 17-49-07.webm](https://github.com/Rafostar/clapper/assets/59534437/8f58f2d5-49ff-4fee-9096-c1ffe3a7e3ae)

**Comment by Gabryoo3** [comment]
If I uninstall clapper and change default app, this choice is respected (I tried before with Handbrake and GNOME respected that decision)

**Comment by Rafostar** [comment]
> Clapper forces itself to open mp3 files

There is no "forcing" in Clapper. The only thing that makes Clapper appear in that list is that Clapper `.desktop` file advertises Clapper as an app that can play this in `MimeType` list.

**Comment by Rafostar** [comment]
@Gabryoo3 
If anything, this would be Nautilus (GNOME Files app) bug, not Clapper. See: https://gitlab.gnome.org/GNOME/nautilus/-/issues/3349

**Comment by Rafostar** [comment]
Nothing to do here, especially seeing that others have similar problems with different apps with Nautilus.
