### ISSUE TITLE
Mysterious missing plugin for type meta/x-gst-fourcc-rtmd

### ISSUE THREAD

**Issue by gregthwuen** [Rafostar/clapper#441]
Trying to play any video recorded with a Sony A6600 or A7IV, Clapper 0.6.0 just shows the warning “Your GStreamer installation is missing a plugin: meta/x-gst-fourcc-rtmd decoder”. Launching with `--gst-debug-level=2`, the output is similiar:

```
0:00:00.493563569 57715 0x71bc38000ff0 WARN                 default descriptions.c:1238:gst_pb_utils_get_codec_description: No description available for media type: meta/x-gst-fourcc-rtmd
0:00:00.493631299 57715 0x71bc38000ff0 WARN            uridecodebin gsturidecodebin.c:1003:unknown_type_cb:<uridecodebin0> warning: No decoder available for type 'meta/x-gst-fourcc-rtmd'.
0:00:00.493704805 57715 0x575ee7980d20 WARN       clapperplaybinbus clapper-playbin-bus.c:189:_handle_warning_msg:<clapperplayer0> Warning: No decoder available for type 'meta/x-gst-fourcc-rtmd'.
```

This seems to be a regression compared to Clapper < 6, since I can't remember ever encountering this problem before upgrading. Here is one of the videos Clapper can't (or won't) play:

https://github.com/Rafostar/clapper/assets/41543402/8cf56dfd-5d12-4a52-86c3-2d924df2854a

While I'm mainly using the [AUR build](https://aur.archlinux.org/packages/clapper), I have also tested the Flathub version to the same result. Launching Clapper under X11 or without hardware acceleration enabled also didn't help. And Totem has no issue playing these video, so I'm pretty sure my system installation of GStreamer is not missing any codecs either.

There are barely any mentions of this codec online, with the only “fixes” for the issue being workarounds (for example [installing the Flathub version of Totem](https://www.reddit.com/r/Fedora/comments/14cohk1/videos_totem_is_not_playing_mp4_file/)). In the GStreamer bug tracker, the codec is not even mentioned once.

Addendum: A known caveat regarding Sony's MP4 files is that the uncompressed audio format is not officially supported by the MP4 container spec, but at least playback never was an issue for GStreamer with these files.

## Debugging Information
GLib 2.80.0
GTK 4.14.3
Adwaita 1.5.0
GStreamer 1.24.3

**Comment by Rafostar** [comment]
Should work now, since you are using AUR, you can try/test with `clapper-git` package.

**Comment by gregthwuen** [comment]
I can confirm it works now, thanks for the fast fix!
