### ISSUE TITLE
Different from other apps background color in initial screen

### ISSUE THREAD

**Issue by M00NJ** [Rafostar/clapper#443]
The background color when opening the app is different compared the other gnome applications. It has a purple tint. 

|Loupe|Decibels|Clapper|
|---|---|---|
|![Screenshot from 2024-05-02 12-16-38](https://github.com/Rafostar/clapper/assets/82398591/35f8ba37-fb00-49af-bc7a-390a53758e04)|![Screenshot from 2024-05-02 12-16-45](https://github.com/Rafostar/clapper/assets/82398591/c4640742-acc6-4084-8f6e-2bc8068e9cf9)|![Screenshot from 2024-05-02 12-16-56](https://github.com/Rafostar/clapper/assets/82398591/34e5f176-8d5c-47cd-a802-c051537831a8)|

Out of curiosity I installed gradience to see how clapper behaves when changing some things around and the background color doesn't get picked up as such it seems.

**Comment by Rafostar** [comment]
Its not "strange", its simply different. I just set it to be like that to better match icon/logo. I dunno if there is any explicit HIG requirement saying that it "must be gray".

**Comment by M00NJ** [comment]
I see, good to know that this is by choice.
I don't know either if it's sated in the HIG anywhere. I pretty sure though that it would be brought up if clapper where to apply to circle or core. But I'm not sure if that's something you would want to do anyways so feel free to close this if you prefer this look... :)
