### ISSUE TITLE
Set common keybindings

### ISSUE THREAD

**Issue by mattiasb** [Rafostar/clapper#45]
Hi!

I just tested out Clapper (seeing it referenced on reddit I believe) and was surprised when `Ctrl+o` didn't let me open a file. :)

The GNOME HIG has a useful list of well-known keyboard shortcuts [here](https://developer.gnome.org/hig/stable/keyboard-input.html.en) and from a quick glance it seems that the following shortcuts would make sense to add:

| **Label**     | **Shortcut**  | **Description**                                                                                                                                                                                       |
| ------------- | ------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Close         | `Ctrl+W`      | Closes the current tab or window. If the window uses tabs and there is only one open, the shortcut should close the window.                                                                           |
| Open…         | `Ctrl+O`      | Opens an existing content item, often by presenting the user with a standard Open File dialog. If the chosen file is already open in the application, raise that window instead of opening a new one. |

**Comment by mattiasb** [comment]
Actually, reading this again, `Ctrl+w` should probably not do anything. I think I tested it with Nautilus (which I'd forgotten actually has tabs) and read the description too quickly.

**Comment by Rafostar** [comment]
We also have an "Open URI" option. Is there some common keybinding for such functionality or some common keybinding for 2nd option from "open menu"? Or will anything do (e.g `Ctrl+u`)?

**Comment by mattiasb** [comment]
That's true!

The closes thing I found was this:
| **Label**     | **Shortcut**  | **Description**                                  |
| ------------- | ------------- | -------------------------------------------------|
| Location…     | `Ctrl+L`      | Allows the user to specify a URI to navigate to. |

That binding *usually* focuses the location bar in applications like Files (Nautilus) or Web (Epiphany) but from its description I think it makes sense to use it for the `Open URI` action. :)

**Comment by mattiasb** [comment]
Also: in the end you're obviously always allowed to use what keybinding you like. :) It's your app! But I think using `Ctrl+O` and `Ctrl+L` makes a lot of sense and are probably relatively well-known bindings from usage of other applications!
