### ISSUE TITLE
Add Pause and Minimize key shortcut

### ISSUE THREAD

**Issue by dougg0k** [Rafostar/clapper#457]
Hi,

I would like to request a feature that is useful sometimes and that it has by default on MPC on Windows and can be added through scripting in MPV.

You press a key and the player are paused and minimized. It's called Boss key. 

Usually by default `b` key are the one used.

**Comment by Rafostar** [comment]
> You press a key and the player are paused and minimized. It's called Boss key.

A "hide before mom sees key" :smile:. Never actually heard about it before, but as long as GTK and WM allows to minimize window programmatically, I do not mind adding it.

**Comment by dougg0k** [comment]
Haha, yeah, I suppose that too.
