### ISSUE TITLE
Youtube urls

### ISSUE THREAD

**Issue by tabzlock** [Rafostar/clapper#46]
The option to open url's is great but unlike some other apps it doesn't support youtube urls. applications such as celluloid support this and I believe it is a great feature and should be implemented.

**Comment by sp1ritCS** [comment]
Celloloid is using mpv as it's backend, mpv has support for youtube-dl and thus you are able to simple insert a youtube url and it'll play.

Clapper is using gstreamer. I've actually played arround with a gstreamer pipeline that can play youtube videos into v4l2loopback. I assume something similar to this could be used to play youtube videos in clapper.

Clapper already has support for playing viddo files, so the only thing It has to do is to check if the inserted url is from youtube, and if so run `youtube-dl --get-url <video id or url>` but I'm unsure how to handle different resolutions/formats

**Comment by tabzlock** [comment]
ok thanks for your response, I assumed it had something to do with the mpv backend. what are the advantages of gstreamer and is there anyway that youtube-dl could be supported in gstreamer?

**Comment by Rafostar** [comment]
The biggest problem with youtube is that Google is throttling the connection speed. As mentioned above mpv uses youtube-dl to do the downloading and youtube-dl is trying to fight against speed throttling by dropping the connection every few seconds and restarting download from the last point until finished.

From what I know youtube does not throttle the so-called "best combined" format (22 for ytdl). GStreamer also can open DASH manifests, so if someone knows of a way to extract them from youtube and if they aren't throttled that could be also used.

> Clapper already has support for playing viddo files, so the only thing It has to do is to check if the inserted url is from youtube, and if so run youtube-dl --get-url "video id or url" but I'm unsure how to handle different resolutions/formats

You can use `-g -f 22` to get "best combined" format. The only format that isn't throttled and copy-paste it to open URI dialog or even launch the app like this from terminal (skip `flatpak run` if this is not a flatpak version):

```sh
flatpak run com.github.rafostar.Clapper $(youtube-dl -g -f 22 "https://www.youtube.com/watch?v=XXXXXX")
```

We can use Soup lib to parse the site, and set different video + audio uris or even convert them to DASH if necessary. The only problem is connection throttling and I would rather avoid anything that involves downloading/caching in the HDD. Clapper already caches URIs to RAM, which makes seeking in them blazing fast (especially with FAST seek mode), so downloading them to HDD like youtube-dl does seems pretty dumb to me.

**Comment by tabzlock** [comment]
ok yeah that makes a lot of sense thanks for the response and a temporary fix. good luck getting this to work I can try and help but I am not very experienced in gstreamer and gjs.

**Comment by Rafostar** [comment]
> I can try and help but I am not very experienced in gstreamer and gjs.

As long as you or anyone else finds a way to get video+audio urls from youtube or DASH manifest in a way that avoids throttling connection by google and doesn't require downloading that video to HDD, I can do the rest.

**Comment by sp1ritCS** [comment]
We might be able to take a look at [Invidious](https://github.com/iv-org/invidious) and how they handle dash video.
I don't like Crystal tho

**Comment by sp1ritCS** [comment]
They actually provide an API that has a provides a dash playlist.

Reqw: `GET https://invidious.snopyta.org/api/v1/videos/M7FIvfx5J10` then get the "dashUrl" key. (in this case https://invidious.snopyta.org/api/manifest/dash/id/M7FIvfx5J10)

I don't know how clapper handles dash, but this 403s for me if I run `com.github.rafostar.Clapper url`

**Comment by Rafostar** [comment]
@sp1ritCS 

Nice find. Can be used for reference.

> I don't know how clapper handles dash

Through [dashdemux](https://gstreamer.freedesktop.org/documentation/dash/dashdemux.html?gi-language=c) element. Nothing special should be needed. Example link from that element docs page works normally with Clapper.

**Comment by sp1ritCS** [comment]
> Example link from that element docs page works normally with Clapper.

yeah, their structures look very different tho. If I see this correct, youtube is using the dash playlist thing only to give various resolutions/variations of a video, not the actual segments of each one.

---

> Example link from that element docs page works normally with Clapper.
actually it segfaults for me after the first segment played. I'll investigate if this still happens on the latest (native/flatpak) version and create an issue.

**Comment by tabzlock** [comment]
Another option similar to invidious newpipe which is written in java could be an option to look at for ideas. Newpipe doesnt block trackers like invidious but it could still possibly have what your looking for.

**Comment by tabzlock** [comment]
Also if any plugins support is coming to this a youtube dl plugin that does similar to what the command you sent me does would be nice for a quick solution.

**Comment by Rafostar** [comment]
I have been playing with this today. The `invidious` is a great workaround. But there is still a ton of work that needs to be done on the player side.

**Comment by tabzlock** [comment]
that was me misclicking the close button oops, Cool hopefully we can see this soon best of luck with an invidious workaround.

**Comment by Rafostar** [comment]
@tabzlock 

The `invidious` is not a very reliable service and I do not want to depend on other hosted sites as proxy here, so it will not be used for this. Still `invidious` was a great help to learn how the things work with YouTube.

**Comment by Rafostar** [comment]
Done the initial implementation. As of now works for most normal 1080p videos. Options to set preferred video resolution, codecs etc. will be added gradually. I will also add an option to do adaptive streaming later on.

@tabzlock 

Hope you appreciate it. It involved a lot of research and my work to get this working.

**Comment by tabzlock** [comment]
Your a legend. Thanks so much for your work.
