### ISSUE TITLE
Imprecise seek bar when a lot of chapters

### ISSUE THREAD

**Issue by dougg0k** [Rafostar/clapper#462]
Hi,

I noticed a possible bug or bad internal settting on the playback/buffer bar, every time I load a 2160p video it lags when trying to change the time, and doesnt seem to be that precise, it feels laggy and it can only skip chunks of time.

I tested with 1080p, that doesnt seem to happen and I know that my machine are not the problem.

I say that might be bad internal setting, as I have experienced this before in bad configured mpv.

Also, I suppose a bigger bar or at least a way to modify the player to make it bigger, would help to make it more precise. As to help skip content you might not want to watch when starting a video.

---

I keep opening issues as I think so far clapper seem to have a decent foundation, other players are not that consistent on linux. VLC are clunky, randomly close when clicking in certain parts of the UI and MPV are good in the configuration but lacks in parts of the UI and sometimes refuse to open, even though there are no process open or hanging.

Would be nice to have one that are consistent supports and have the best parts of each, available, or at least modular enough to modify.

**Comment by Rafostar** [comment]
I haven't experienced the "lagging" part. Can you show this problem so I can see what exactly happens to you (with e.g. screen recording)? Also, is this Xorg or Wayland? What video decoder is used (info window shows it's name)?

**Comment by dougg0k** [comment]
Sure, here you go. 

https://www.dropbox.com/scl/fi/wv0i5vn37vkc7mwe7bxbw/2024-06-15_11-25-54.mp4?rlkey=xwwsgsc40g7vdqo9jh77iqw4k&st=y02sls9r&dl=0

I am on PopOS 22.04, so X11. Video decoder included in the video.

**Comment by Rafostar** [comment]
As far as I see, this is expected behaviour. GTK makes slider knob "click" into position of chapter mark. This makes easier for user to seek into exact chapter position. It's just that in this video there are a lot of chapters so it sticks into one and when moved, it already reaches another chapter and keeps sticking between them.

**Comment by dougg0k** [comment]
You're right. Still it doesnt feel precise when looking to get to a specific position, maybe a bigger and wider bar would help here, tweaks to the chapter sliding to not behave as it is too much, still have the easy to reach each chapter, while not affecting the rest. If possible.

**Comment by dougg0k** [comment]
Also if there were a way to get the position changes in realtime, rather than having to release to see that, would be easier to see where you are in that specific time. At least have this as an option.
