### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by kelixirr** [Rafostar/clapper#472]
Missing plugin GStreamer installation is missing a plugin text/html decoder. What to do? I was trying to copy YouTube URL and play in it

**Comment by Rafostar** [comment]
> What to do?

You can either install Clapper Flatpak package and have it working out of the box or alternatively install/compile [gtuber](https://github.com/Rafostar/gtuber) and export/set `CLAPPER_USE_PLAYBIN3=1` when running Clapper.

Please use either Clapper matrix channel or at least github "Discussions" for asking support questions. Lets use issue tracker for tracking issues.

**Comment by kelixirr** [comment]
Hello, that's why I pointed out here. It's not working properly. Please check.

**Comment by Rafostar** [comment]
I already answered your question what to do. Clapper uses GStreamer and GStreamer is modular. If you want to play something you need a plugin for it. In normal package from distro repos you have ability to add whichever plugin you want, but you install (or maybe even make :smile: ) plugins yourself. On the other hand Flatpak package tries to include as many plugins as possible, but you cannot extend its functionality.
