### ISSUE TITLE
Missing plugin: Decoder meta/x-gst-fourcc-mett

### ISSUE THREAD

**Issue by nadrolinux** [Rafostar/clapper#477]
Hello,
It looks like the latest version of Clapper from Flatpak has a problems with opening videos recorded with Pixel 6 phones (probably with other Pixels too). When I open sample video I just see an error about missing plugin:

> Decoder meta/x-gst-fourcc-mett

I attached sample video here:
https://e.pcloud.link/publink/show?code=XZGiDgZQi4PG4inmVmDrbRYUqR1mQVDMsty
With older (< 0.6.0) Clapper I could open videos without problem.

Anyway thanks for this great video player!

**Comment by Rafostar** [comment]
This should be **fixed in 0.6.1**. Please check if you have **installed/updated** to this version **AND** if you are using Flatpak package **from Flathub** source.

**Comment by Rafostar** [comment]
> It looks like the latest version of Clapper from Flatpak has a problems

Attached sample plays fine for me using 0.6.1 version from Flathub.

**Comment by nadrolinux** [comment]
Hi,
I have 0.6.1 from Flathub, but attached video doesn't work for me. I have Fedora Silverblue 40 + AMD Radeon RX 6000 XT GPU.

Output from `flatpak list | grep Clapper`:
`Clapper	com.github.rafostar.Clapper	0.6.1	stable	system`

Output from `flatpak list | grep org.freedesktop.Platform`:
```
Freedesktop Platform	org.freedesktop.Platform	freedesktop-sdk-23.08.21	23.08	system
i386	org.freedesktop.Platform.Compat.i386		23.08	system
Mesa	org.freedesktop.Platform.GL.default	24.1.3	23.08	system
Mesa (Extra)	org.freedesktop.Platform.GL.default	24.1.3	23.08-extra	system
Mesa	org.freedesktop.Platform.GL32.default	24.1.3	23.08	system
Mesa (Extra)	org.freedesktop.Platform.GL32.default	24.1.3	23.08-extra	system
ffmpeg-full	org.freedesktop.Platform.ffmpeg-full		23.08	system
i386	org.freedesktop.Platform.ffmpeg_full.i386		23.08	system
openh264	org.freedesktop.Platform.openh264	2.1.0	2.2.0	system
openh264	org.freedesktop.Platform.openh264	2.4.1	2.4.1	system
```

Maybe should I manually install some Freedesktop/Gnome platform extension?

**Comment by Rafostar** [comment]
Hmm. Seems to be simply a language/locale issue that makes current workaround not work in this case.
