### ISSUE TITLE
Piped videos usually stream in the worst possible quality

### ISSUE THREAD

**Issue by TriVoxel** [Rafostar/clapper#487]
## Description

Videos streamed from [Piped](https://github.com/TeamPiped/Piped/), (as is the case when using the embedded Clapper widget in [Pipeline](https://gitlab.com/schmiddi-on-mobile/pipeline/)), videos have a very high variable resolution and this leads to hitching, stuttering, and really questionable audio and video quality.

I feel like we really need a way to force a resolution and to only load that quality stream. This could be in the quick settings under the video tab. It seems like this UI exists to support this feature, but it doesn't work.

## Test this

1. [Install Pipeline](https://flathub.org/apps/de.schmidhuberj.tubefeeder)
2. Open Pipeline
3. Search an HD video
4. Play a video
5. Note the extremely unreliable video quality, even on good internet.

**Comment by Rafostar** [comment]
Pipeline streams from YT, not Piped. The constant quality fluctuations should be improved in its latest update 2.0.2.

AFAIK, the only related inconvenience left is that videos start playing with worst quality for the first few seconds, afterwards it goes higher (up to 1080p currently).

**Comment by TriVoxel** [comment]
> Pipeline streams from YT, not Piped. The constant quality fluctuations should be improved in its latest update 2.0.2.
> 
> AFAIK, the only related inconvenience left is that videos start playing with worst quality for the first few seconds, afterwards it goes higher (up to 1080p currently).

Thanks for the clarification. I was testing the beta, not realizing a stable build with these improvements had already released. Upon re-evaluating, I can confirm it is resolved!
