### ISSUE TITLE
Flatpak runtime branch is EOL, please update

### ISSUE THREAD

**Issue by Scotty-Trees** [Rafostar/clapper#502]
Currently on Fedora 41, Gnome 47 and after running `flatpak update` I came across this warning. Please update to the lastest flatpak runtime, thank you. 

```
Looking for updates…

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
com.github.rafostar.Clapper
```

**Comment by Rafostar** [comment]
I see you found [the same issue](https://github.com/flathub/com.github.rafostar.Clapper/issues/30) already open in Flathub repo, so closing this one.
