### ISSUE TITLE
App window is almost entirely translucent

### ISSUE THREAD

**Issue by folknor** [Rafostar/clapper#53]
Hi,

So I apologize beforehand in case this is a known issue or has been previously reported (though I did search, and looked through closed issues as well). It just feels like a problem you'd already know about, but I could not find anything.

I built and ran clapper locally like this:
```
$ git clone https://github.com/Rafostar/clapper
$ cd clapper
$ meson build --prefix=/usr/local
(... fails once or twice while I install missing deps, etc ...)
$ ninja -C build
$ sudo ninja -C build install
$ com.github.rafostar.Clapper
```

And the result is a window that is almost entirely translucent, except for a few parts like the bottom bar and the top-right window controls. I've attached a screenshot of it running over a black empty terminal, and one with it showing a video over the same terminal.

Note how even with a video playing, you can clearly see the terminal behind it.

I've also attached logs from meson and ninja.

An entirely separate issue, but it looks to me like the controls (bottom bar) are slightly blurry as well.

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1070/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 460.56

Linux plantasjen 5.12.0-051200rc2-generic #202103052202 SMP Sat Mar 6 06:06:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

3   │ X.Org X Server 1.20.10
   4   │ X Protocol Version 11, Revision 0
   5   │ [     4.364] Build Operating System: linux Ubuntu
   6   │ [     4.364] Current Operating System: Linux plantasjen 5.12.0-051200rc2-generic #202103052202 SMP Sat Mar 6 06:06:18 UTC 2021 x86_64
   7   │ [     4.364] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.12.0-051200rc2-generic root=UUID=7730f8dd-102c-4889-b2eb-29a4075f3383 ro quiet splash vt.handoff=7
   8   │ [     4.365] Build Date: 22 February 2021  10:54:42AM
   9   │ [     4.365] xorg-server 2:1.20.10-3ubuntu3 (For technical support please see http://www.ubuntu.com/support) 
  10   │ [     4.365] Current version of pixman: 0.40.0
```
[install-log.txt](https://github.com/Rafostar/clapper/files/6131732/install-log.txt)
[meson-log.txt](https://github.com/Rafostar/clapper/files/6131733/meson-log.txt)
[dot_ninja_log.txt](https://github.com/Rafostar/clapper/files/6131737/dot_ninja_log.txt)
![clapper-video](https://user-images.githubusercontent.com/233791/110975344-89123f80-8357-11eb-802c-41cfce9b0dbb.png)
![clapper-empty](https://user-images.githubusercontent.com/233791/110975067-2de04d00-8357-11eb-9891-b64db493169d.png)

**Comment by folknor** [comment]
Gnome-shell 3.38.4, X11, mutter v3.38.3-3ubuntu2, mesa 20.3.4-1, gtk4 v4.0.3-4, gstreamer1.0-gl v1.18.3-1

**Comment by Rafostar** [comment]
> It just feels like a problem you'd already know about, but I could not find anything.

This is not a known problem. In fact, its the first time I see something like that. In addition to being weirdly half-transparent and blurry around the edges it also seems a little squashed at the bottom. The only thing that comes to mind is that you are on Nvidia GPU, so it might be a Nvidia driver bug, but might also be some weird system theme applied that causes this. I do not have a PC with Nvidia at hand to test.

Do you have similar problems when you run examples from `gtk4-demo` app? After resizing for e.g. "Gears" demo? Also if you have Intel iGPU, did you try booting with it to confirm that this is not a Nvidia bug?

**Comment by folknor** [comment]
`gtk4-demo` produces an entirely white window. There's a text cursor when I hover some parts of it, and when I select some text and then type in Firefox, the `gtk4-demo` window flickers "randomly", showing parts of itself as I type each letter.

When using the super key to show the windows in Gnome, the window renders partially. Attached is a screenshot of that.

So this is probably not your bug. Yours is the first GTK4 app I've tried, as far as I know.

![gtk4-demo](https://user-images.githubusercontent.com/233791/110982842-ee1e6300-8360-11eb-8bd0-c6bc683f8fa3.png)

**Comment by folknor** [comment]
And unfortunately no, I don't have an iGPU to try.

**Comment by Rafostar** [comment]
OK. Since this happens to you on all GTK4 applications I will close this as not my bug. You should probably open this as an issue on GTK gitlab to let them know that such problems exists if no one else did that yet.

**Comment by folknor** [comment]
If I'm not mistaken, the OpenGL renderer backend is getting a rewrite post-gtk-4.0, so I'm not going to bother filing a bug about it now.

Just for posterity, for anyone who finds this issue in a web search, using the `GSK_RENDERER` environment variable set to `cairo` or `vulkan` (it defaults to `opengl`) makes things render. Vulkan renderer seems slightly buggy in some places like fonts in popup menus are blurrier than other fonts, but I found open bugs about these things.

Unfortunately Clapper doesn't (currently?) seem to work with the `vulkan` renderer, but seems to work using `cairo`.

I realise there's no need for further discussion in this ticket, like I said - I write this for people who stumble across this ticket later.

**Comment by Rafostar** [comment]
New renderer is now included and used by default since GTK 4.2.0. This GTK4 version is now also included in Flatpak package. If the problem persists, please report it on GTK gitlab (if it wasn't already).

**Comment by folknor** [comment]
Here we go; https://bugzilla.mozilla.org/show_bug.cgi?id=1714483

This is the setting in nvidia-settings: https://i.stack.imgur.com/U3NR0.png

Fascinating bug. I had indeed enabled global FXAA probably a decade ago for whatever reason. Disabled that, and Clapper and Firefox popups now render correctly, plus gnome-shell no longer sometimes freaks out and completely breaks the font rendering globally, which it used to do every few days (and has been doing for at least a few years.)

Note the nvidia developer replies in that ticket, and also note the env var `__GL_ALLOW_FXAA_USAGE=0`.

**Comment by Rafostar** [comment]
Thanks for a follow up. Recently GTK devs reworked their GL init code for GTK 4.4 to be compatible with Nvidia Wayland session with 470 drivers. I wonder if this gonna introduce or fix more issues for Nvidia users.

**Comment by folknor** [comment]
https://www.nvidia.com/download/driverResults.aspx/180483/en

Note this part: `Added an application profile to disable FXAA for Firefox to prevent visual corruption.` They're simply not aware that it's not just Firefox. It's all GTK apps, including the shell itself.

It's probably the second line here, from `nvidia-application-profiles-470` which installs as `/etc/nvidia/nvidia-application-profiles-rc`:
```
        { "pattern": "firefox",          "profile" : "ForceSeparateTrimThread" },
        { "pattern": "firefox",          "profile" : "FA0" },
```
[nvidia-application-profiles-470.74-rc.txt](https://github.com/Rafostar/clapper/files/7198490/nvidia-application-profiles-470.74-rc.txt) (renamed to .txt for github)

I have no idea how any of this affects Wayland. I've yet to try it. I probably will in a year or two when things stabilize a bit more and I can expect most things to work.
