### ISSUE TITLE
Implement translations

### ISSUE THREAD

**Issue by juxuanu** [Rafostar/clapper#58]
I see there are UI elements marked as "translatable" but there is no `po` directory ready for people to translate.

**Comment by Rafostar** [comment]
Most of the words that needs translating are in preferences and open URI dialogs. All dialogs are temporary placeholders now (until `libadwaita` is available to package managers). No point translating twice (text will be probably changed).

**Comment by Rafostar** [comment]
Most of the app should be now translatable. Translating can be done easily using Crowdin: https://crowdin.com/project/clapper
