### ISSUE TITLE
Error: Failed to convert video buffer

### ISSUE THREAD

**Issue by laconick** [Rafostar/clapper#59]
```
Unable to create a GL context
```
That's the message I get from Clapper installed (flatpak) on a Librem 5 phone. I can't play any videos.

**Comment by Rafostar** [comment]
OpenGL rendering in GTK4 (that Clapper uses) requires OpenGL 3.2 or later. AFAIK Librem 5 only supports OpenGL 2.0 at the moment. You might be able to use OpenGL ES:
```sh
GDK_DEBUG=gl-gles flatpak run com.github.rafostar.Clapper
```
You can also try forcing Cairo rendering with `GSK_RENDERER=Cairo` if above fails. There is also a total software enforcement flag: `LIBGL_ALWAYS_SOFTWARE=1`.

Preferably we should use OpenGL (or ES), but I dunno what Librem 5 is capable of. In case of Pinephone, I heard that software renderer works better than its mesa GL driver, so you might experiment. I don't own either of the mobile devices unfortunately.

GTK4 is unable to autodetect and use OpenGL ES at the moment (which is what mobile devices usually have). I heard there were plans to add a build option for GTK4 to compile with ES by default. You should ask GTK4 devs for more info/progress on that matter.

If any of the above variables helps you, then you can add it to your `Environment` for permanent solution.

**Comment by laconick** [comment]
Thank for your quick reply.
Unfortunately nothing seems to be working. But I realize it's not your fault.
FYI here is the output of the commands suggested; I cannot work this out:

```
purism@librem5: $ GDK_DEBUG=gl-gles flatpak run com.github.rafostar.Clapper

(com.github.rafostar.Clapper:3): Gtk-WARNING **: 18:00:14.866: Broken accounting of active state for widget 0xaaab13b2a260(GtkGstGLWidget)

(com.github.rafostar.Clapper:3): Gtk-WARNING **: 18:00:14.868: Broken accounting of active state for widget 0xaaab13a10350(GtkOverlay)

(com.github.rafostar.Clapper:3): Gtk-WARNING **: 18:00:14.868: Broken accounting of active state for widget 0xaaab13a101e0(Gjs_ClapperWidget)

(com.github.rafostar.Clapper:3): Gtk-WARNING **: 18:00:14.868: Broken accounting of active state for widget 0xaaab139ca3e0(GtkApplicationWindow)

(com.github.rafostar.Clapper:3): Gdk-WARNING **: 18:00:28.807: Server is missing xdg_foreign support

(com.github.rafostar.Clapper:3): Gtk-WARNING **: 18:00:28.807: Failed to export handle, could not set transient for

(com.github.rafostar.Clapper:3): Clapper-CRITICAL **: 18:00:39.122: Error from element /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:vbin/GstGLSinkBin:glsinkbin0/GstGLColorConvertElement:glcolorconvertelement0: Resource not found.
Failed to convert video buffer
../ext/gl/gstglcolorconvertelement.c(224): gst_gl_color_convert_element_prepare_output_buffer (): /GstPlayBin:playbin/GstPlaySink:playsink/GstBin:vbin/GstGLSinkBin:glsinkbin0/GstGLColorConvertElement:glcolorconvertelement0

```
where Clapper-CITICAL happens while trying t open a video.

```
purism@librem5:~$ GSK_RENDERER=Cairo flatpak run com.github.rafostar.Clapper

(com.github.rafostar.Clapper:3): Clapper-CRITICAL **: 18:03:11.746: Unable to create a GL context
```
And `LIBGL_ALWAYS_SOFTWARE=1` doesn't work either.

**Comment by Rafostar** [comment]
In the output:

> (com.github.rafostar.Clapper:3): Gdk-WARNING **: 18:00:28.807: Server is missing xdg_foreign support

Missing "xdg_foreign" support is a Librem 5 Phosh issue:
[https://source.puri.sm/Librem5/phoc/-/issues/90](https://source.puri.sm/Librem5/phoc/-/issues/90)

From the output you send, I assume that you actually managed to start the app and select some video to play, yes? If you create some folder (e.g. named "graphs") in your "Videos" directory and start the app with below and try opening a video:
```sh
GST_DEBUG_DUMP_DOT_DIR=~/Videos/graphs GDK_DEBUG=gl-gles flatpak run com.github.rafostar.Clapper
```
Do you get some files created there when playback should start? If yes, could you send them to me? (they will contain the video file name and a filepath to it inside. No other private data. Just warning you :smile:)

You can also try debugging GStreamer to see what is going on wrong:
```
GST_DEBUG=4,*gl*:7 GDK_DEBUG=gl-gles flatpak run com.github.rafostar.Clapper
```

**Comment by laconick** [comment]
Yes, the application starts, the message I reported appears in the middle of Clapper window.
`GST_DEBUG_DUMP_DOT_DIR` doesn't create any files.
GStreamer debug outputs a lot of things, attached is the result.
[output.txt](https://github.com/Rafostar/clapper/files/6217899/output.txt)

**Comment by Rafostar** [comment]
The meaningful part of the output where it fails:

```sh
0:00:37.908841400  0xffff480ed9e0 DEBUG              glupload gstglupload.c:2003:_upload_find_method:<glupload0> attempting upload with uploader GLMemory
0:00:37.909026795  0xaaaac3e0ae40 TRACE             glcontext gstglcontext.c:1554:_gst_gl_context_thread_run_generic:<glcontextegl0> running function:0xffff76a9cd54 data:0xffff5c044100
0:00:37.909066154  0xaaaac3e0ae40 INFO              glconvert gstglcolorconvert.c:2197:_init_convert: Initializing color conversion from I420 to RGBA
0:00:37.909206550  0xffff5c041760 DEBUG          glbasememory gstglbasememory.c:187:gst_gl_base_memory_init: new GL buffer memory:0xffff4816e590 size:107264
0:00:37.909271228  0xffff5c041760 DEBUG         glbasetexture gstglmemory.c:353:gst_gl_memory_init: new GL texture context:<glcontextegl0> memory:0xffff4816e590 target:2D format:6403 dimensions:240x416 stride:256 size:107264
0:00:37.909356426  0xaaaac3e0ae40 DEBUG                  glsl gstglsl.c:677:_mangle_external_image_extension: is oes? 0, profile == ES? 0, version >= 300? 0, have essl3? 0
0:00:37.909558620  0xaaaac3e0ae40 WARN                   glsl gstglsl.c:546:gst_gl_version_to_glsl_version: unknown GL version
0:00:37.909591619  0xaaaac3e0ae40 ERROR             glslstage gstglslstage.c:345:gst_glsl_stage_set_strings:<glslstage0> GL context does not support version 110 and profile compatibility
0:00:37.909624978  0xaaaac3e0ae40 ERROR             glconvert gstglcolorconvert.c:2045:_create_shader:<glcolorconvert0> Failed to create vertex stage
0:00:37.909653897  0xaaaac3e0ae40 TRACE              glshader gstglshader.c:124:gst_gl_shader_finalize:<glshader0> finalizing shader 0
0:00:37.909680896  0xaaaac3e0ae40 DEBUG              glshader gstglshader.c:110:_cleanup_shader: shader deleted 0
0:00:37.909735735  0xffff480ed9e0 WARN       glconvertelement gstglcolorconvertelement.c:224:gst_gl_color_convert_element_prepare_output_buffer:<glcolorconvertelement0> error: Failed to convert video buffer
```

**Comment by Rafostar** [comment]
@laconick 

Quote from Wikipedia:
> Librem 5 features an i.MX 8M Quad Core processor, with an integrated GPU which supports OpenGL 3.0, OpenGL ES 3.1, Vulkan 1.0 and OpenCL 1.2 with default drivers;[26] however, since the driver used is the open source Etnaviv driver, it at present only supports OpenGL 2.1 and OpenGL ES 2.0.

So we should be able to use OpenGL 2.1 or ES 2.0.

GTK4 by default requires and uses OpenGL 3.2+, but can also use ES 2.0+ with `GDK_DEBUG=gl-gles` otherwise GL context creation will fail. Next GTK4 version will automatically use ES when OpenGL is older than 3.2, so thats OK. Until next version is released you need to use `GDK_DEBUG=gl-gles`.

The `Error: Failed to convert video buffer` from your output is a different issue. By default GStreamer also uses OpenGL, but version 2.1 (that Librem 5 is supposed to have) in this case is enough for video playback to work. For some reason your GPU driver "etnaviv" fails to create OpenGL 2.1 context and succeeds with 1.3 only, which is too low to handle color conversion in coming buffers. I am not familiar with Librem 5, so I cannot tell why that happens.

One thing you can try is to also force GStreamer to use GLES 2:
```sh
GST_GL_API=gles2 GDK_DEBUG=gl-gles flatpak run com.github.rafostar.Clapper
```
an output of this command with prefixed `GST_DEBUG=4,*gl*:7` like you send me before would also be welcome.

**Comment by laconick** [comment]
That worked!
Attached is the output of the command that includes a video opening.
[out.zip](https://github.com/Rafostar/clapper/files/6222206/out.zip)

**Comment by Rafostar** [comment]
So only GLES for Librem 5 it seems :thinking:

Once next GTK4 ver is out I will test if the recent commit I pushed to Clapper git makes the GLES selection in GStreamer also automatic. I heard that there is progress on getting hardware acceleration for Librem 5 too, so hopefully everything will work much faster and "out of the box" soon.

**Comment by laconick** [comment]
Thank you very much
