### ISSUE TITLE
Top left menu disappeared

### ISSUE THREAD

**Issue by thegarlynch** [Rafostar/clapper#66]
![114407304-c9075500-9b97-11eb-9c49-264b4d7ec2fd](https://user-images.githubusercontent.com/36429132/114713658-df8ce800-9d20-11eb-9c81-14111208fe17.png)

Possible Causes : 
- Switching from KDE (and randomly configure something, i don't know what) and back to Gnome
- Update to Gnome 40

**Comment by Rafostar** [comment]
@thegarlynch 

Yeah, if you switched to KDE that might have caused this as it might have changed app menu settings.

Are you using Flatpak version or native package? There is a chance I fixed this in recent Clapper update. Did you update Clapper to 0.2.0 and problem persists?

**Comment by thegarlynch** [comment]
Flatpak version, i noticed that you already fixed jagged text, thank you for that. But top left bar problem still persists

**Comment by Rafostar** [comment]
Output of below please:
```
DEBUG=Clapper flatpak run com.github.rafostar.Clapper
```
It should have some slight hint at what I am looking for in the first few lines.

**Comment by thegarlynch** [comment]
Clapper initializing GNOME Shell DBus proxy +63.482ms
Clapper headerbar layout: icon,spacer,minimize,maximize,close +182.429ms
Clapper set audio-video offset: 0 +42.730ms
Clapper set subtitle-video offset: 0 +76µs
Clapper changed play flags: 1559 -> 1687 +148µs
Clapper user selected theme: Adwaita +20.925ms
Clapper set volume icon: high +207.260ms
Clapper monitor application-pixels: 1366x768 +6.830ms
Clapper restored window size: 598x415 +134µs
Clapper GNOME Shell DBus proxy is ready +6.278ms

**Comment by Rafostar** [comment]
@thegarlynch 

> headerbar layout: icon,spacer,minimize,maximize,close

OK. So this is an unusual system config for GNOME. Normally it should have either a "menu" or "appmenu" in this list. Otherwise it is telling applications to place menus somewhere outside of app. I do not support that. Lets try resetting it to defaults.
```
gsettings reset org.gnome.desktop.wm.preferences button-layout
```

**Comment by thegarlynch** [comment]
It works!! Thank You!!
