### ISSUE TITLE
Show main menu button in fullscreen

### ISSUE THREAD

**Issue by legacychimera247** [Rafostar/clapper#68]
well simply enough, it would be nice to have the ability to open a video while in fullscreen, if it's already there anyway i don't see the button...

**Comment by Rafostar** [comment]
`Ctrl+o` should work. I might consider leaving the top left open menu button in fullscreen if it will be an often requested feature.

**Comment by legacychimera247** [comment]
well i think it would be useful because you could then, make use of the "start in fullscreen" option...

**Comment by Tuxino88** [comment]
> well i think it would be useful because you could then, make use of the "start in fullscreen" option...

yes the auto fullscreen function does not work

![Schermata da 2021-04-26 12-01-55](https://user-images.githubusercontent.com/75674245/116065362-3bdbfa00-a687-11eb-8960-8e5a3b5d4c76.png)

**Comment by Rafostar** [comment]
> yes the auto fullscreen function does not work

"auto fullscreen" means "go fullscreen after opening a video file unless we are in floating mode". Does that work? Once prefs are ported to libadwaita I will do short descriptions of those options, cause I know that some of them like this one do not say what they actually are supposed to do.

**Comment by Tuxino88** [comment]
> > yes the auto fullscreen function does not work
> 
> "auto fullscreen" means "go fullscreen after opening a video file unless we are in floating mode". Does that work? Once prefs are ported to libadwaita I will do short descriptions of those options, cause I know that some of them like this one do not say what they actually are supposed to do.

ah okok , yes if I open a video goes directly to full screen
