### ISSUE TITLE
Xorg: crash on open volume popover then enter fullscreen

### ISSUE THREAD

**Issue by legacychimera247** [Rafostar/clapper#70]
well seems that clapper crashes on this occasion

steps  to reproduce

1 open clapper
2 open the volume bar
3 double click to full screen
4 clapper crashes

think this may be helpful...

```
(com.github.rafostar.Clapper:14857): Gdk-CRITICAL **: 00:14:46.425: gdk_surface_request_layout: assertion 'frame_clock' failed

(com.github.rafostar.Clapper:14857): Gdk-WARNING **: 00:14:46.426: The program 'com.github.rafostar.Clapper' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 3440 error_code 3 request_code 12 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by Rafostar** [comment]
I am aware of various issues like this under Xorg. Those are `GTK4` issues, so nothing I can do about them here. Because of that (and many other reasons) is why I recommend Wayland. The situation in `GTK4` seems to be getting better with each new release through.

Are we talking about Flatpak version from Flathub or did you install Clapper locally from package or build it? If the later then, what is your `GTK4` version?

**Comment by legacychimera247** [comment]
I know about wayland, but i'm on xorg due to nvidia card, anyway, it's an rpm downloaded with the terminal from your repo, and for the record, i'm actually on fedora 33, gtk4 is the latest released for the distro...

**Comment by Rafostar** [comment]
@legacychimera247 

> fedora 33, gtk4 is the latest released for the distro

Which would be 4.0.3 if I see correctly. GTK4 is still quite new and unpolished. I know that situation has improved in GTK 4.2.0 and still is getting better with each new GTK4 version.

Fedora 34 should be out within next week or two with GTK 4.2.0 AFAIK. I would recommend updating, then to check if problem is still there. You can also build GTK4 yourself from git or you can try installing Clapper Flatpak version - it has the latest GTK4 + few additional GStreamer patches. If the `X errors` are still there in latest GTK, you should open an issue on GTK gitlab.

GTK4 problems cannot be fixed here, but in GTK4 itself. Thanks for understanding.

**Comment by legacychimera247** [comment]
the problem still persist, thank you for the explanation anyway...

**Comment by legacychimera247** [comment]
i noticed that this does appear with all the popup menues that clapper have, maybe if it's not a clapper fault you know where i can report those?

**Comment by Rafostar** [comment]
@legacychimera247 

Like I said, its a GTK4 problem. It should be reported on GTK gitlab: [https://gitlab.gnome.org/GNOME/gtk](https://gitlab.gnome.org/GNOME/gtk)

**Comment by legacychimera247** [comment]
hello, just wanna to point out that as of now, the issue is finally solved...
