### ISSUE TITLE
mkv glitch 

### ISSUE THREAD

**Issue by Tuxino88** [Rafostar/clapper#71]
```
libva info: VA-API version 1.11.0
libva info: Trying to open /usr/lib64/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_11
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.11 (libva 2.9.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 21.2.0 (ddf7bbce)
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileVP8Version0_3          :	VAEntrypointVLD

```

https://user-images.githubusercontent.com/75674245/116009467-3399a580-a61a-11eb-83b6-defa7da9c1b7.mp4

**Comment by Rafostar** [comment]
This one seems like either simply a broken video file or some GStreamer matroska parser bug. Does this happen in every video or only this one? If this one only, then throughout whole video or just in this single scene?

**Comment by Tuxino88** [comment]
You're right, sorry for reporting, I don't have any other films in MKV I hadn't checked, however strange with MPV does not occur, maybe it's a Gstreamer problem with this specific video

**Comment by Rafostar** [comment]
@Tuxino88 

If GStreamer matroska parser/decoder has problems with this video but mpv doesn't, it would be useful to do a little debugging and report that problem on GStreamer gitlab. So it can be improved.

**Comment by Tuxino88** [comment]
> @Tuxino88
> 
> If GStreamer matroska parser/decoder has problems with this video but mpv doesn't, it would be useful to do a little debugging and report that problem on GStreamer gitlab. So it can be improved.

I will try some other videos first before reporting, maybe it is the video that has some
