### ISSUE TITLE
Flatpak: Cannot drag video file into Clapper

### ISSUE THREAD

**Issue by vchernin** [Rafostar/clapper#75]
Dragging a video file from Nautilus into the Clapper Flatpak window does nothing.

I expect the video to start playing.

I believe this is a Flatpak issue [[1]](https://github.com/flatpak/xdg-desktop-portal/issues/99)[[2]](https://github.com/flatpak/flatpak/issues/1143)[[3]](https://github.com/flathub/io.github.celluloid_player.Celluloid/issues/16), if so it could be added to #35.
Interestingly the third link says GTK 4 should fix it, but clearly there is more to it.

Distro: Fedora 34 silverblue

**Comment by Rafostar** [comment]
@vchernin 

In case of GTK4 both applications between you drag file "from" and "to" has to be made with GTK4. Without GTK4 file manager, you can D&D contents of `~/Videos` directory (with sub-directories) or you can also override default Clapper Flatpak permissions to add access to more directories.

**Comment by vchernin** [comment]
When dragging a video from most directories I indeed get an error.
```bash
flatpak run com.github.rafostar.Clapper
(com.github.rafostar.Clapper:2): Clapper-CRITICAL **: 19:20:34.351: file does not exist: /var/home/<user>/<video file>
```
When I drag a video from `~/Videos` no error is produced, and the video plays.
So the behaviour is exactly as described.

Thank you clarifying that the "from" app also needs to be GTK4. I wonder if QT 6 and Flutter would also work with the file-transfer portal.

Since the proper fix is in the UI toolkits, this Clapper issue should probably be closed.

Perhaps it's worth adding a mention of this behaviour to the Clapper wiki?

**Comment by vchernin** [comment]
[Upstream GTK 3 bug](https://gitlab.gnome.org/GNOME/gtk/-/issues/3094) (for Nautilus portal support)

**Comment by Rafostar** [comment]
To clarify for others: either backporting that portal to GTK3 or porting Nautilus to GTK4 will do the trick.

**Comment by AbrarSL** [comment]
This still doesn't work with Nautilus 43.

**Comment by AbrarSL** [comment]
I tried this with Nautilus 44 as well. It still doesn't work. Can this issue be reopened?

**Comment by Rafostar** [comment]
Now that it is supported in Nautilus, guess we still miss something to get portal working here, so reopening.

**Comment by Rafostar** [comment]
With next version, we will likely move into a playback queue model. So I will try to ensure this is properly implemented then and I will try to change how this works into a way, that one can drag file directly into a position in a queue.

**Comment by Rafostar** [comment]
This seems to work correctly now in latest git (pending 0.6.0 version). If still a problem, please reopen.
