### ISSUE TITLE
Make it harder to accidentally remove plugins.

### ISSUE THREAD

**Issue by tomfitzhenry** [Rafostar/clapper#79]
In the preference window, I clicked the "-" button to see what it did.

![Screenshot from 2021-06-10 21-25-12](https://user-images.githubusercontent.com/61303/121517266-ae5a2c80-c9de-11eb-86b0-1b269c6c761c.png)

The plugin was removed from the list, and I was left with no indication how to get the plugin back. I wasn't expecting the plugin to be disabled (after all, I could have done that by unchecking "Apply"), so I didn't remember the plugin string to easily re-add it.

Ideas for improvements:
* Remove the ability to remove plugins.
* Add a tooltip
* Add undo?

I could try to avoid clicking unknown buttons, too.

Version: 2.1

**Comment by Rafostar** [comment]
@tomfitzhenry 

Do not worry. This window does not remove plugins from your system. Only from the list. This is just a custom configuration of available gstreamer plugins. Just click the "+", a new row will appear and fill it back.

**Comment by Rafostar** [comment]
@tomfitzhenry 

Considering that this only alters the plugin list and their configs (not touching files), I do not think there should be any warnings like that. It is already under "Advanced" settings and users can easily restore the list by either resetting the `gsettings` via terminal or writing it back. The `vah264dec` plugin was added there **just for being an example**. Once it is considered stable in GStreamer and enabled by default I might remove it from this list by default.

> Version: 2.1

BTW: The current version is 0.2.1, and not 2.1 :-)
