### ISSUE TITLE
Make ui more consistent

### ISSUE THREAD

**Issue by SeaDve** [Rafostar/clapper#82]
I found the ui sometimes confusing since the fullscreen and unfullscreen button are in different places. On the top and at the bottom when full screen. It would be more coherent if it stays on the same corner.

Another thing is the playback controls, I think it look better if it is either always floating or always acting like a panel instead of two different look.

One more thing, possibly maybe automatically hide/show the playback controls depending on where the cursor is like other players.

Lastly, I want to thank you for the application. I already replaced totem, and this works really well, although, there is stuttering when using hardware acceleration, but probably my hardware

**Comment by Rafostar** [comment]
> I found the ui sometimes confusing since the fullscreen and unfullscreen button are in different places.

This is debatable, I guess. Someone will probably say "I prefer them in single place" or "its better cause more of the title fits the screen" while another would want "consistent look". :man_shrugging: 

> Another thing is the playback controls, I think it look better if it is either always floating or always acting like a panel instead of two different look.

Panel hides for a specific use-case - "floating window" i.e. a PiP like video that **stays above all other windows**. This makes it easier to see if keep above is on/off. And having the panel always shown below video makes it easier to see and seek video chapters and also track current progress. I imagine most people either watch videos fullscreen or with floating mode to have it play while they browse net.

> there is stuttering when using hardware acceleration, but probably my hardware

Decoding is handled by GStreamer, rendering by GTK4. I would start by checking if both `vaapi` and `va` plugins reproduce this issue in Clapper and also in `gtk4-demo` app (there is a demo player in it, although it handles video buffers differently then I do). Then eventually test performance with `glimagesink` (to skip GTK4). If you dunno how or have other questions, a good place to ask would be [Clapper Matrix channel](https://matrix.to/#/#clapper-player:matrix.org) as this is unrelated to the issue you opened here.

**Comment by SeaDve** [comment]
> its better cause more of the title fits the screen

What do you mean? It's possible to get the best of both worlds, with proper design

>  I imagine most people either watch videos fullscreen or with floating mode to have it play while they browse net.

I mean to point the playback control panel. It is floating when full screen, hidden when pip, a panel when normal window. I think it looks more coherent if all of them is either floating or a panel. Probably simpler floating on pip. I'll possibly create mockups, if you agree with the design.

--------------
 
With the last one, it is not always reproduceble, but ill contact again/ open separate issue if i manage to check those

**Comment by Rafostar** [comment]
> I mean to point the playback control panel. It is floating when full screen, hidden when pip, a panel when normal window. I think it looks more coherent if all of them is either floating or a panel. Probably simpler floating on pip. I'll possibly create mockups, if you agree with the design.

Seen GNOME Videos mockups? They would be basically what you ask for, I guess:
[https://gitlab.gnome.org/Teams/Design/app-mockups/-/raw/9a3f0d898f0dce82f798c93390cadb949f858cc2/videos/videos.png](https://gitlab.gnome.org/Teams/Design/app-mockups/-/raw/9a3f0d898f0dce82f798c93390cadb949f858cc2/videos/videos.png)

Clapper was already partially following them in some places (I notified the person who designed those, so its ok). There are a few issues with those through, e.g. having time labels on the sides of scale with changing number of characters would be way too problematic. I cannot even begin to imagine a non-disturbing transition from 2 rows to 1 on controls panel. The size difference between labels (time especially) and video subtitles when fullscreen would be too big, etc.

Thus Clapper ended with transforming single row controls panel. It is inconsistent and rather unique compared to every other video player I have seen (that might be good actually), but it works and (at least I think) it looks good in each of these use-cases.
