### ISSUE TITLE
Add symbolic icon

### ISSUE THREAD

**Issue by SeaDve** [Rafostar/clapper#83]
It also provides better support with high contrast. Plus, better consistency with other gnome apps

**Comment by Rafostar** [comment]
A MR would be much appreciated.

**Comment by SeaDve** [comment]
Not a designer, but i'll try

**Comment by Rafostar** [comment]
@SeaDve 

I am not a designer either. Thanks anyway for your effort. I will leave this open with "help wanted" tag, so if you cannot manage, don't worry, hopefully someone else will grant your request :-)

**Comment by SeaDve** [comment]
![image](https://user-images.githubusercontent.com/64297935/122489662-be8f8e80-d012-11eb-9f4a-6eab193d6829.png)
Here's my take

**Comment by Rafostar** [comment]
Merged
