### ISSUE TITLE
Better touch support

### ISSUE THREAD

**Issue by Schmiddiii** [Rafostar/clapper#93]
I would really like better support for touch screens.
Currently playing and pausing is only supported by clicking on a tiny button in the bottom left corned.
Furthermore seeking does not seem supported at all, only using the keyboard (if I missed something please tell me).

Therefore I would like to propose a hopefully better system using double-tabs on the video:

![Clapper](https://user-images.githubusercontent.com/48252573/125960000-0bc7eca1-d575-4466-a16d-1bd3611ea104.png)

- The red and green areas would seek forward or backward
- The yellow area would toggle fullscreen
- The blue area would play/pause

I am already using a similar system in mpv using plugins and it is something I really miss from clapper.

As this would probably interfere with desktop-users this probably should be a setting.
These proposal should probably be discussed as the areas include the features I would use and maybe not the features the majority will use.

**Comment by Rafostar** [comment]
> Furthermore seeking does not seem supported at all, only using the keyboard (if I missed something please tell me).

In fullscreen, you can swipe horizontally to seek forward/backward by the amount of time configured in preferences. Alternatively you can tap the screen to reveal OSD controls and seek by dragging slider.

**Comment by Rafostar** [comment]
Unless you are on Xorg, cause now I see that touch to reveal OSD indeed does not work there.

**Comment by Schmiddiii** [comment]
I already new you can drag on the slider, but it feels imprecise.
The sliding is a nice tipp and will do it for me.

I still would like to see a easier way to play/pause as double tapping in the middle of the screen seems better than bringing up controls and clicking the play/pause button.
Maybe switching right- and leftclick may do it (similar to #18).
This is of course just personal preference.

P.S: No I use Wayland on the Pinephone but nice to see that I indirectly found a bug.

**Comment by Rafostar** [comment]
Blue and yellow seem too confusing. You can just double tap to toggle fullscreen, but GTK seems to expect high accuracy in the coordinates of first and second tap (same place).

Since we do swipes to seek, maybe I can add red and green eventually to switch videos/tracks?

Also, out of consideration of users who run full GNOME desktop all of the touch/gestures needs to be enabled in fullscreen only, otherwise it would prevent dragging window with touch.

**Comment by Rafostar** [comment]
@Schmiddiii 

You can now do a press and hold to toggle play/pause.

**Comment by Schmiddiii** [comment]
Thank you, works perfectly.
Closing this as all the features I wanted are now implemented.
