### ISSUE TITLE
Remember playback speed

### ISSUE THREAD

**Issue by Schmiddiii** [Rafostar/clapper#94]
The playback speed should probably be persistent in between videos.

A preferences-area similar to `Volume` would also be beneficial.

**Comment by erazemk** [comment]
+1, but for videos in a session/playlist (so when opening multiple videos).

**Comment by Rafostar** [comment]
I think this should be persistent overall (also between app launches) for consistency with other options (volume, subtitles enabled state and queue progression mode, etc.).

> A preferences-area similar to Volume would also be beneficial.

Preferences-area volume setting will be removed in next release to make life easier. You change an option, it gets changed, its kept and restored. Simple and consistent.
